### ISSUE TITLE
[Bug]: Using same credentials, in CRM and storefront does not work correctly

### ISSUE THREAD

**Issue by Furman1331** [medusajs/medusa#10049]
### Package.json file

```JSON
{
  "name": "medusa-next",
  "version": "1.0.3",
  "private": true,
  "author": "Kasper Fabricius Kristensen & Victor Gerbrands (https://www.medusajs.com)",
  "description": "Next.js Starter to be used with Medusa server",
  "keywords": [
    "medusa-storefront"
  ],
  "scripts": {
    "dev": "next dev -p 8000",
    "build": "next build",
    "start": "next start -p 8000",
    "lint": "next lint",
    "analyze": "ANALYZE=true next build",
    "test-e2e": "playwright test e2e"
  },
  "dependencies": {
    "@headlessui/react": "^1.6.1",
    "@hookform/error-message": "^2.0.0",
    "@medusajs/js-sdk": "2.0.0",
    "@medusajs/ui": "2.0.0",
    "@meilisearch/instant-meilisearch": "^0.7.1",
    "@paypal/paypal-js": "^5.0.6",
    "@paypal/react-paypal-js": "^7.8.1",
    "@stripe/react-stripe-js": "^1.7.2",
    "@stripe/stripe-js": "^1.29.0",
    "algoliasearch": "^4.20.0",
    "axios": "^1.6.7",
    "i18next": "^23.16.4",
    "jwt-decode": "^4.0.0",
    "lodash": "^4.17.21",
    "next": "^14.0.0",
    "pg": "^8.11.3",
    "qs": "^6.12.1",
    "react": "^18.2.0",
    "react-country-flag": "^3.0.2",
    "react-dom": "^18.2.0",
    "react-instantsearch-hooks-web": "^6.29.0",
    "react-intersection-observer": "^9.3.4",
    "server-only": "^0.0.1",
    "superagent": "^10.1.1",
    "tailwindcss-radix": "^2.8.0",
    "webpack": "^5"
  },
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@medusajs/types": "2.0.0",
    "@medusajs/ui-preset": "2.0.0",
    "@playwright/test": "^1.41.1",
    "@types/lodash": "^4.14.195",
    "@types/node": "17.0.21",
    "@types/pg": "^8.11.0",
    "@types/react": "^18.2.42",
    "@types/react-dom": "^18.2.18",
    "@types/react-instantsearch-dom": "^6.12.3",
    "@types/superagent": "^8.1.9",
    "ansi-colors": "^4.1.3",
    "autoprefixer": "^10.4.2",
    "babel-loader": "^8.2.3",
    "eslint": "8.10.0",
    "eslint-config-next": "^13.4.5",
    "postcss": "^8.4.8",
    "prettier": "^2.8.8",
    "tailwindcss": "^3.0.23",
    "typescript": "^5.3.2"
  },
  "packageManager": "yarn@3.2.3"
}
```

### Node.js version

v20.5.1

### Database and its version

PostgresSQL 16.2

### Operating system name and version

MacOS Sequoia 15.0.1

### Browser name

Brave

### What happended?

While login with my credentials to CRM. I've got correct response, but while trying to login with same credentials at storefront, in response I've got 200 with jwt in cookies which is incorect behavior. This JWT token wont allow me to open /account/dashboard, because it should not be generated, it happens because user and customer use same fields in database without any difference.

You probably need to change the logic in the auth routes, as you currently only recognise which provider you should use.

### Expected behavior

Separate authentication logic based on which type of user is trying to authenticate.

### Actual behavior

Logic connects customer and user, but does not work corectlly.

### Link to reproduction repo

Medusa Starter

**Comment by olivermrbl** [comment]
@Furman1331, this is the expected behavior of our authentication flows. You can read more about it in our [documentation](https://docs.medusajs.com/resources/commerce-modules/auth#main).

The flow goes like this:

**Sign up as customer**
- `POST /auth/customer/emailpass/register` -> Create an auth identity
- `POST /store/customers` -> Use the token from the register call to register as a customer

Now, the auth identity you created in the first API call can be used to assume more than just the customer role. For example, let's say you want to allow "company employees" to sign up as well. Those company employees can be the same individual as your customer, so you would reuse the underlying auth identity.

**Sign up as employee (provided you are already a customer)**
- `POST /auth/employees/emailpass` -> Return the auth identity
- `POST /stores/employees` -> Use the token from the authenticate call to register as an employee

This is exactly the reason for the possibly unintuitive behavior you are seeing when trying to use a user account in the storefront. You are getting a 200 + token because your auth identity exists; however, you cannot use the token as you are not signed up as a customer.

I hope this makes sense.
