### ISSUE TITLE
[Bug]: Changes not reflected when using `medusa-dev-cli`

### ISSUE THREAD

**Issue by Bradzer** [medusajs/medusa#10075]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prettier": "^3.3.3",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

20.14.0

### Database and its version

16.3

### Operating system name and version

Linux Mint 21.2 Cinnamon

### What happended?

When using `medusa-dev-cli` to link a customized fork of the Medusa monorepo with a backend repository, the changes made in the customized fork are not reflected when starting the backend.

For instance when changing this:
```ts
// packages/admin/dashboard/src/routes/users/user-list/components/user-list-table/user-list-table.tsx

// ... rest of the file
<Heading>{t("users.domain")}</Heading>
// ... rest of the file
```

To this:
```ts
// packages/admin/dashboard/src/routes/users/user-list/components/user-list-table/user-list-table.tsx

// ... rest of the file
<Heading>MY CUSTOM HEADING</Heading>
// ... rest of the file
```
After getting the changes in the backend repository by running `medusa-dev` and then starting the backend, the heading still shows `Users` when navigating to `http://localhost:9000/app/settings/users`.

### Expected behavior

The changes made in the customized Medusa should be reflected in the backend.

### Actual behavior

The changes made in the customized fork are not reflected when starting the backend.

### Link to reproduction repo

N/A

**Comment by kasperkristensen** [comment]
Hi @Bradzer,

We aren't actively maintaining the `medusa-dev-cli` and currently we are only keeping it around because it's used for one of our CI actions. Once that action has been updated, we will most likely remove the package entirely.

Our usual workflow is to use `yarn link` to create resolutions for the local versions of the different Medusa packages, when we are working on them. 

When working with `/dashboard` specifically my usual workflow is to simply run `yarn dev` inside of the project, and add `localhost:5173` to ADMIN_CORS in your server. You can add the following to a .env file in the dashboard project to link it to your local server:

```
VITE_MEDUSA_PROJECT=Users/kasper/work/server/src/admin
VITE_MEDUSA_BACKEND_URL=http://localhost:9000
``` 

VITE_MEDUSA_PROJECT tells the dashboard where to load Admin extensions from, so if you want to load extensions in development you should point it to where your server project is located. You can also omit it if you don't care about extensions. VITE_MEDUSA_BACKEND_URL sets the URL that is used to make requests.

Hope this helps, as we won't be fixing the dev-cli to work with the dashboard project.
