### ISSUE TITLE
error creating storefront from template

### ISSUE THREAD

**Issue by dev1-tazlabs** [medusajs/medusa#10398]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

error creating storefront from template
npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa bazar21-storefront
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: medusa-next@1.0.3
npm error Found: react@19.0.0-rc-66855b96-20241106
npm error node_modules/react
npm error   react@"19.0.0-rc-66855b96-20241106" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@">=16.8.0" from @hookform/error-message@2.0.1
npm error node_modules/@hookform/error-message
npm error   @hookform/error-message@"^2.0.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.

### How can this issue be resolved?

1. firsat time I try so don't know how to resolve
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by EduardoZepeda** [comment]
Same error,  using node v20.11.1 after running `npx create-medusa-app@latest`.

**Comment by itsluap** [comment]
Same issue here, was just working fine last night though.

**Comment by kasperkristensen** [comment]
You need to use `npm install --legacy-peer-deps` as the error suggests. Next uses a pre-release version of React which does not strictly satisfy the peerDependency requirements of @hookform/error-message, which is why you are seeing this error. There should however be no issue despite this since react@16.8 and react@19-rc are compatible, so by passing the flag `--legacy-peer-dependency` will allow the install to go through.
