### ISSUE TITLE
Implement a default price selection strategy

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#1137]
Implement a default price selection strategy for outputting prices and moneyamounts in a meaningful way depending on context

The strategy should have the following methods
  1. `calculateLineItemPrice` which should take the following arguments (to be used with creating line items): 
        1. cart_id
        2. customer_id (optional)
        3. region_id (derived from the cart)
        4. lineItem
    2. `calculateVariantPrice` which should take the following arguments (to be used when listing products): 
        1. cart_id
        2. customer_id (optional)
        3. region_id (derived from the cart)
        4. variant

The strategy should return an object like the following: 
```
{
	originalPrice: number
	calculatedPrice: number
	prices: MoneyAmount[] // prices is an array of all possible price for the input customer and region prices
}
``` 

Acceptance criteria: 
- A `DefaultPriceSelectionStrategy` is present in the `/strategies` folder along with an appropriate interface in the `/interfaces` folder (note: not in medusa-interfaces)

**Comment by srindom** [comment]
Just a couple of nits and thoughts here:

- Could we maybe just stick with `calculateVariantPrice` and then instead of `lineItem` which is missing give the option of passing a `quantity`. This way when generating a LineItem we will pass the quantity which is what can affect the pricing. 

- If writing out the entire signature for the method I think it should be something like this:
```ts
type PriceSelectionContext = {
  cart_id?: string
  customer_id?: string
  region_id?: string
  quantity?: number
}

async calculateVariantPrice(variantId: string, context: PriceSelectionContext): Promise<PriceSelectionResult>
```
