### ISSUE TITLE
Research: Update FileService to allow for protected uploads/downloads + streaming

### ISSUE THREAD

**Issue by kasperkristensen** [medusajs/medusa#1269]
**Goal**
Research how providers such as S3, DO, etc. so the FileService can serve as an abstraction over how these handle protected upload/downloads and streaming.

**DoD**
- [ ] Create a small write-up outlining an approach for supporting protected uploads and downloads in generic way

**Comment by pKorsholm** [comment]
This is more an exploration into how we can handle file streaming securely with the existing file services, however the methods are general for S3, Minio and spaces. They seem very standardized in how different operations are handled which could lead one to believe that these are generalized across most fileservices. I think the operations and how they are outlined below would generally allow us to handle uploads in a generic way for the existing file services and hopefully be generic enough to expand to other services.

**Upload to fileservice**

To upload a `.csv` file to a fileservice, we should be able to use streams as it seems like standard practice to be able to stream upload files. This way we could continually write to whatever input stream is being used to upload the file.

Passthrough streams seem like an ideal fit for this purpose. It’s a function on streams in the core node library that essentially passes all read bytes from input to output. Passthrough with pipes as described here would probably allow us to upload a csv file to s3 bit-by-bit: [https://stackoverflow.com/questions/37336050/pipe-a-stream-to-s3-upload](https://stackoverflow.com/questions/37336050/pipe-a-stream-to-s3-upload), the input to  

[https://nodejs.org/api/stream.html#class-streampassthrough](https://nodejs.org/api/stream.html#class-streampassthrough)

**User Download**

For user download we, in the core, dont need to do any continuous  streaming. As far as I can tell both amazon, minio and digital ocean support authenticated/presigned links to authenticated resources. They all have expiration as well which we can use to control the lifetime of the links. Given that the links are just to download the files the lifetime of a link should be so small that it essentially becomes a one time download

amazon: [https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html#RESTAuthenticationQueryStringAuth](https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html#RESTAuthenticationQueryStringAuth)

minio: [https://docs.min.io/docs/javascript-client-api-reference.html#presignedGetObject](https://docs.min.io/docs/javascript-client-api-reference.html#presignedGetObject)

DO: [https://docs.digitalocean.com/products/spaces/resources/s3-sdk-examples/#presigned-url](https://docs.digitalocean.com/products/spaces/resources/s3-sdk-examples/#presigned-url)

**Download from fileservice** 

To download files from the file service chunk by chunk in order to continually process the files to be imported both Minio, S3 both support getting parts of a file outlined by a pointer and chunk size. Since DO uses the S3 API for spaces and supports Object CRUD according to their documentation the way to download from aws and download from S3 should be the same or similar(their documentation is not the best and i haven’t seen in it any.

To download a file we could create a specialized batch stream which we depending on the file service change the implementation of but when read returns the content of a file in chunks (similarly to the [[dev.to](http://dev.to/)](http://dev.to) article but for each file service).

![image](https://user-images.githubusercontent.com/88927411/168034890-0087b179-f9ad-496b-906a-85ccfba94572.png)

[https://docs.min.io/docs/javascript-client-api-reference.html#getPartialObject](https://docs.min.io/docs/javascript-client-api-reference.html#getPartialObject)

[https://dev.to/about14sheep/streaming-data-from-aws-s3-using-nodejs-stream-api-and-typescript-3dj0](https://dev.to/about14sheep/streaming-data-from-aws-s3-using-nodejs-stream-api-and-typescript-3dj0)

### Export

This would be the simplest of the two cases we operate in since the operation would involve generating and streaming an export file to the file service installed which, as described above, should be possible using passthrough streams and pipes. After upload a presigned download link can be generated using the file provider and be passed back through the api.

### Import

For import we need to allow the user to upload a file to the file system. I found this thread on Stack overflow which might be interesting to experiment with: [https://stackoverflow.com/a/59165218](https://stackoverflow.com/a/59165218). Since S3 and minio both support pre-signed urls for upload as well as download, we could try to pipe the request on to the file service in order to allow uploads directly. 

The alternative to this would be to have the API stream the file to the fileservice as it is read. This example uses BusBoy: [https://levelup.gitconnected.com/upload-and-stream-multipart-content-with-nodejs-in-5minutes-61836e061080](https://levelup.gitconnected.com/upload-and-stream-multipart-content-with-nodejs-in-5minutes-61836e061080), but other tools exist.

### api extension

For the above changes to be possible the file service should be extended with a couple of methods. Initial draft:

```javascript
generatePresignedDownload(resource)
generatePresignedUpload(resource) 

getUploadStream(fileMetaData)
getDownloadStream(resource)
```

This didn't really end up being a small write-up but let me know what you think 😄

**Comment by adrien2p** [comment]
don't see much to say actually :joy: as you mention normally those platforms  allows to just generate signed url that you then send to the client to be consumed. Which means we just need to return that string url.

About downloading/uploading stream files, the only concern I have is multer, I think that you can't handle the streams directly, we have to create a new storage to be able to allow that. Then we only play with `Readable` and `Writable` or `PassThrough` for both upload and download. Don't see any other particular difficulties.

for the service API we could go for 
```ts
upload(file)
download(fileData)
uploadStream(name: string; file: Readable): Promise<string>
downloadStream(fileData): Readable -> that we pipe into the res  writable
getSignedUrl(fileData): string
```
