### ISSUE TITLE
Research: Parsing CSV file server-side

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#1485]
**Goal**
Research and identify a library or util for parsing a CSV file from a request

**DoD**
- [x] Create a small write-up outlining an approach for parsing CSV

**Comment by zakariaelas** [comment]
I think a great candidate is [papaparse](https://www.papaparse.com/). I think it's the most popular csv parser on npm. Played around with it and I like it so far. Also found this really cool [article](https://leanylabs.com/blog/js-csv-parsers-benchmarks/) that benchmarks between different libraries out there. I think the performance is pretty good even for a 100x100k (cols vs rows) csv file.

I also tried papaparse using streams on the tekla dataset I shared on slack and it looked like this:
```typescript
const fileStream = fs.createReadStream('filename.csv')
const papaStream = Papa.parse(Papa.NODE_STREAM_INPUT, {
  dynamicTyping: true,
  header: true
});

fileStream.pipe(papaStream)

papaStream.on('data', data => {
  console.log(data)
})

papaStream.on('finish', () => {
  console.log('done')
})
``` 

Also, papaparse is also very "fast" in browser environments. Although we previously talked about doing most of the work on the server, it might be worth keeping in mind that the library has a few features which makes it great to work with even client-side by supporting workers and streaming out of the box. 

As always, feel free to pitch in!

**Comment by adrien2p** [comment]
@zakariaelas I really think that the work should always be done by the server and not the client. The reason is that each time we are doing computational task, if we choose to do it client side, then it leans that we are not in control of the machine and it can be a user we a huge machine or another one with just a small machine in a third country. When the task is done server side we are more in control of the environment and w are sure to guarantee to performance. Other point is the network and bandwidth, for the same reason, this is why ssr can be good because then you don't depends on the client machine or at least there is less work to do for the client computer 😊.

I hope that it is understandable, let me know your thoughts 💭

**Comment by zakariaelas** [comment]
@adrien2p for sure! Sorry I think I might have misled you with my comment. It was not my intention to argue in favor of doing processing client side, rather, I just wanted to mention **one of** the advantages of papaparse, which might be worth considering when deciding between different parsing libraries 😄 .

**Comment by olivermrbl** [comment]
I am up for going with `papaparse`. Think we should aim to decide on a tool as fast as possible and proceed to the actual parsing of the products, since this is where the limitations of the libraries will prob. show them selves.
