### ISSUE TITLE
Wholesale accounts / pricing method

### ISSUE THREAD

**Issue by dan5082** [medusajs/medusa#1703]
Hello I’m wondering if there is a good way to set up a separate section of the store to allow wholesale customer account creation and pricing. Is the best way to do this currently a new sales channel?

**Comment by olivermrbl** [comment]
We recently released a PriceList API allowing you to define product variant prices specific to customer groups. This should cover your use case.

You will need to:
1. Create a customer group in Medusa Admin to hold your wholesale customers (or a group for each customer)
2. Create a PriceList in Medusa Admin specific to these customer groups
3. Allow your customers to sign up through your storefront
4. Assign customers to groups after having signed up

Let me know if it makes sense @dan5082 !

**Comment by dan5082** [comment]
That sounds like it will work, thank you! Does it also allow to apply price changes for the shipping options as well?

**Comment by AlexDigital974** [comment]
@dan5082 
We are doing something a bit similar to what you want . But definitely  the PriceList API is the way to go and its working. 
We are pulling the prices from External System(ERP)->put it in via PriceList API ( need to link to a customer_groups which itself is link to customer).
And its working even with the starter Gabsy storefront it will show up the correct price.Amasing.

Regarding Shipping as far as i know, it is only link to Regions. Although you can have multiple profile with different options it is not link to customers .

So in my opinion (not an expert) the easiest none shenanigans way of adding custom shipping price per customer  without invoking 5k line of code 😸 and waiting the feature to be added:

Is just to use customer.metadata (existing fields) something like **metadata: { mypersonalCustomVipShippingPrice: value }**

[https://docs.medusajs.com/api/store/customer/create-a-customer] <---check api doc.

you could even add it to your medusa backend ,since metadata is a default field it will trivial to display.
<img width="634" alt="Screenshot 2022-06-22 at 1 04 37 PM" src="https://user-images.githubusercontent.com/89772505/174949868-efed2dfc-54fb-41cf-a5de-ccba110dadfb.png">

In frontend you can have a very simple logic to say  hey : 

if  (customer is vip/b2b and he has that **customer.metadata?.mypersonalCustomVipShippingPrice** set up) 
shipping_amount = customer.metadata?.mypersonalCustomVipShippingPrice

Else standard shipping profile amount apply.

**Comment by olivermrbl** [comment]
Closing for now. Let me know if you want to continue the discussion or have any follow up questions @dan5082

**Comment by BorisKamp** [comment]
@olivermrbl I also want to use price lists. However, I'm not using the medusa SDK for customer login as I have our customers in a Strapi CMS which syncs with Medusa. The user is authenticated in our storefront with a strapi user bearer. On their profile they have a Medusa customer id.

How can I make sure to show them the correct prices? None of the GET product, list products and cart endpoint have a native option for this it seems?
