### ISSUE TITLE
Keep showing up These credentials do not match our records

### ISSUE THREAD

**Issue by topmask** [medusajs/medusa#1864]
Follow this tutorial Deploy Medusa Admin on Netlify

Keep showing up These credentials do not match our records

(https://docs.medusajs.com/deployments/admin/deploying-on-netlify/)

server status

```
❯ medusa develop
Successfully compiled 0 files with Babel (3ms).
[medusa-config] ⚠️ jwt_secret not found. fallback to either cookie_secret or default 'supersecret'.
[medusa-config] ⚠️ cookie_secret not found. fallback to either cookie_secret or default 'supersecret'.
✔ Models initialized – 37ms
✔ Plugin models initialized – 3ms
✔ Repositories initialized – 63ms
✔ Database initialized – 160ms
✔ Strategies initialized – 8ms
✔ Services initialized – 130ms
✔ Express intialized – 21ms
✔ Plugins intialized – 11ms
✔ Subscribers initialized – 9ms
✔ API initialized – 50ms
⠙ Initializing defaultswarn:    You don't have any notification provider plugins installed. You may want to add one to your project.
⠹ Initializing defaultswarn:    You don't have any taxProviders provider plugins installed. You may want to add one to your project.
✔ Defaults initialized – 351ms
⠋ Initializing search engine indexingwarn:    No search engine provider was found: make sure to include a search plugin to enable searching
✔ Indexing completed – 14ms
✔ Server is ready on port: 9000 – 33ms


```

set administrator
```
medusa user --email o@gmail.com --password 1234568

```

server  .env
```
#CORS admin
ADMIN_CORS=https://admin.xxx.com
```

medusa-config.js
```
// CORS when consuming Medusa from admin
const ADMIN_CORS = process.env.ADMIN_CORS || "https://admin.xxx.com,http://localhost:7000";
```

environment variable

GATSBY_MEDUSA_BACKEND_URL
value  http://ip address:9000

Unable to enter the management interface

**Comment by adrien2p** [comment]
Is the user created in the right database? I mean, if you run the command locally, is the config pointing to the same db as the deployed server?

**Comment by topmask** [comment]
want to install locally
Appear

<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'mini-css-extract-plugin /html/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[1].use[1]!/html/node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[1].use[2]!/html/src/assets/styles/global.css|0|Compilation/modules|/html/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[1].use[1]!/html/node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[1].use[2]!/html/src/assets/styles/global.css': No serializer registered for Warning
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 1 items } -> webpack/lib/ModuleWarning -> Warning

**Comment by olivermrbl** [comment]
Did you manage to resolve your issue @topmask ?

**Comment by topmask** [comment]
The problem is solved
thank you

**Comment by chillpilllike** [comment]
@topmask  How you manage to solve the issue. I am facing exactly the same issue.

**Comment by wernet** [comment]
@topmask, I also am having the same issue.

How were you able to solve the problem?

Thanks,

Bill

**Comment by adaltonreis** [comment]
> @topmask How you manage to solve the issue. I am facing exactly the same issue.

Hi kindly, since you opened this issue, it would be great if would could share the solution or what was (possibly) the mistake!

This Github issue was one of the first results when I searched for the `medusjas "These credentials do not match our records"`  on Goggle. 

Would you have  a minute to post the solution of your particular case, please?

Thank you!

**Comment by adaltonreis** [comment]
> The problem is solved thank you
Hi kindly, since you opened this issue, it would be great if would could share the solution or what was (possibly) the mistake!

This Github issue was one of the first results when I searched for the medusjas "These credentials do not match our records" on Goggle.

Would you have a minute to post the solution of your particular case, please?

Thank you!

**Comment by adaltonreis** [comment]
> The problem is solved thank you

Hi kindly, since you opened this issue, it would be great if would could share the solution or what was (possibly) the mistake!

This Github issue was one of the first results when I searched for the ```medusjas "These credentials do not match our records"``` on Goggle.

Would you have a minute to post the solution of your particular case, please?

Thank you!
