### ISSUE TITLE
Use correct payload type for resetting password in `medusa-js`

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#2019]
**What**
Method [`resetPassword`](https://github.com/medusajs/medusa/blob/aaebb38eae883a225779b03556900ea813c991d2/packages/medusa-js/src/resources/customers.ts#L85) in the Customers domain of `medusa-js` currently uses the wrong payload type. 

Should be changed to `StorePostCustomersResetPasswordReq`

**Comment by sabakhilji** [comment]
Hi, @ olivermrbl can I do this? Although I am a beginner, as far as I know, this issue is regarding a change in file customer.ts and the path of the file is (https://github.com/medusajs/medusa/blob/master/packages/medusa-js/src/resources/customers.ts). There is a method resetPassword there and it has a payload type :StorePostCustomersCustomerPasswordTokenReq , this needs to be changed, right?

**Comment by olivermrbl** [comment]
@sabakhilji Yes indeed! Would be great 💪

**Comment by sabakhilji** [comment]
Should I start a PR @olivermrbl?

**Comment by olivermrbl** [comment]
Sure!

**Comment by sabakhilji** [comment]
Thanks!

**Comment by algren123** [comment]
Happy to take this on if still needed 👍

**Comment by varun7singh** [comment]
Is this issue still open?

**Comment by sabakhilji** [comment]
Hi, @Varun Singh this issue has been resolved thanks!

**Comment by agdm** [comment]
please close?

**Comment by pevey** [comment]
@olivermrbl et al 
Sorry to pester, I know you all are super busy.

There are 2 issues currently marked as "good first issues."  I was going to try to clear them, but it seems they have already been resolved but not closed.

If so, when you get a moment, could you please close them and maybe mark some new issues that are relatively straightforward as good first issues?  Trying to get more familiar with the medusa code base so that maybe I can contribute more.
