### ISSUE TITLE
Creating shipment with claimService does not add tracking links

### ISSUE THREAD

**Issue by macder** [medusajs/medusa#2042]
### Describe the bug

When creating a shipment via `claimService.createShipment` it does not add tracking links to the fulfillment. The `tracking_links` property is missing on the fulfillment object. 

It does however mark the shipment as shipped, just no tracking links

### System information

Medusa version (including plugins): 1.3.5
Node.js version: 17.1.0
Database: postgres:10.4
Operating system: Ubuntu 18.04
Browser (if relevant):

### Steps to reproduce the behavior

1. Create a claim for an order
2. Create a fulfillment for the claim order
3. Create a shipment for the claim fulfillment, eg:

```javascript
const test = await claimService.createShipment(claim_id, ful_id, [
    {
      tracking_number: "track",
      url: "https://www.usps.com/tracker/123",
    },
  ])
```
Then observe the fulfillment object, notice there is no `tracking_links` prop

### Expected behavior

Tracking links should be saved to the fulfillment

**Comment by srindom** [comment]
@macder - thanks for reporting; I think the tracking links are on the fulfillment but are not showing up in Admin because the tracking links are not joined when querying the order. 

Should be a fairly quick fix by just adding `"claims.fulfillments.tracking_links"` here: https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/admin/orders/index.ts#L260

Will have it included in the next release :)

**Comment by macder** [comment]
@srindom Glad to hear that it was an easy quick fix. 

Thanks for the quick turnaround :)
