### ISSUE TITLE
Update data and metadata fields from PaymentSession and Cart using RESTAPI

### ISSUE THREAD

**Issue by benhammoush** [medusajs/medusa#2252]
Hi,

I'm using the nextjs create-medusa-app template.

I'm trying to pass datas about orders / payments (strings) from the storefront to the admin panel.
I thought i could use both data and metadata fields from PaymentSession and Cart arrays but i'm unable to update them.

I tried using : 

```
const medusa = new Medusa({ baseUrl: MEDUSA_BACKEND_URL, maxRetries: 3 })
medusa.carts.update(cart.id, {
  metadata: 'test'
})

```

it returns 400 error (Error: property metadata should not exist)

```
const medusa = new Medusa({ baseUrl: MEDUSA_BACKEND_URL, maxRetries: 3 })
  await medusa.carts.updatePaymentSession(cart.id, 'manual', {
    data: { "test" : "test"
    }
  })

```

it returns 500 error (TypeError: provider.withTransaction(...).updatePaymentData is not a function)

i also tried using cURL but not working. 

Any idea on how this should be properly done ?

Thanks

**Comment by olivermrbl** [comment]
Thanks for reporting this one @benhammoush!

You are faced with the 500 due to a missing method implementation in our manual payment provider. I've added it in #2254 and will release a new version as soon as it is merged.

In the meantime, you can either use this canary version that I've published `medusa-payment-manual@1.0.17-manual-pay-fix.0` or remove the `medusa-manual-payment` plugin and use Stripe (or similar) instead. 

Hope this helps!

**Comment by seanwyndellque** [comment]
We're also having issues setting the metadata field for cart and getting the same 400 error (Error: property metadata should not exist).

**Comment by olivermrbl** [comment]
It is currently not possible to update metadata on carts. I will attend to an update allowing you to do so and include it in an upcoming release.

Until then, you can use the `context` on the cart to store custom attributes.

```curl
curl --location --request POST 'http://localhost:9000/store/carts/some_cart_id' \
--header 'Content-Type: application/json' \
--data-raw '{
    "context": { "key": "value" }
}'
```

**Comment by benhammoush** [comment]
Using context does the job for me, thanks 👍
