### ISSUE TITLE
Medusa with NODE_ENV="production"

### ISSUE THREAD

**Issue by thelastcoming** [medusajs/medusa#2314]
### Describe the bug

Medusa server working as expected when it's in development mode once switching to production users can't login.

### System information

Medusa version (including plugins): 1.3.3
Node.js version: 1.3.3
Database: PostgreSQL or SQlite both have same issue
Operating system: FreeBSD 13.1
Browser (if relevant): Chromium & Firefox

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by adrien2p** [comment]
When set to production the cookies are secure. It means that you can't use http and you must use https instead. If you deploy your projects they also must not be on a domain which is part of the public suffix list

**Comment by thelastcoming** [comment]
Hi,
I am getting this error in production mode
![image](https://user-images.githubusercontent.com/111051475/193726506-2c442325-d899-4398-835e-371a98cee656.png)
But in the mean time when I switch to development mode it works fine

**Comment by R3D2** [comment]
I have the same issue.

**Comment by DaveLomber** [comment]
Same issue here

**Comment by leikoilja** [comment]
Same issue happens for me with `NODE_ENV=production` on self-hosted environment.
Even tho both are under the same parent domain:
- https://admin.dokku.example.com
- https://backend.dokku.example.com

couldn't yet figure out what is the issue with cookies and it being set correctly :/ Everything works fine with `NODE_ENV=development`.

@R3D2, @DaveLomber, have any of you managed to solve it?

**Comment by adrien2p** [comment]
Is your domain part of the public suffix list?

**Comment by leikoilja** [comment]
@adrien2p, sorry, what is "public suffix list"? 😅 
my domain is `admin.dokky.mydomain.com` where `mydomain` is just a random work like `orange`(actually pretty similar, just another type of fruit haha) 😅

**Comment by chemicalkosek** [comment]
@leikoilja Public Suffix List is a maintained list of suffixes where setting cookies is limited: <https://publicsuffix.org/>
Mostly this is related to herokuapp, vercel, netlify domains etc.
If you use your own domain, it doesn't apply to you.
I see you use dokku and probably have your own domain. It should all work if you have set the SSL certificate.
I also use dokku and never had any issues with that. Do you set SSL certificate with Dokku Let's Encrypt plugin?

For anyone in this thread. If NODE_ENV is set to `production` the cookie is `secure`. Hence it needs SSL certificate.
I would crosscheck those points:
- Domains should not be on Public Suffix List
- SSL certificate on all domains (https)
- admin, storefront and backend under the same main domain i.e. mydomain.com, backend.mydomain.com, admin.mydomain.com
- COOKIE_SECRET is set
- Redis needs to be set up (it acts as express session store)

I've also seen users having problems when using some proxies (nginx, apache) and/or things like Cloudflare.
The issue is when SSL is not set for all the layers. Or maybe there's a proxy setting that needs to be set.
If there's a misconfiguration here, the cookie will also not be set. I would look somewhere here if all the above points are crosschecked.

For reference:
https://github.com/medusajs/medusa/issues/1498#issuecomment-1229122157
https://github.com/expressjs/session/issues/251#issuecomment-188617002
https://okhlopkov.com/cloudflare-certificates-dokku/
https://spiffy.tech/dokku-with-lets-encrypt-behind-cloudflare

**Comment by leikoilja** [comment]
Hey, @chemicalkosek. 
Thanks for the detailed breakdown.
Indeed I do use dokku with my own domain behind nginx proxy.

I actually noticed a similar SSL issue with my other project and suspect that it might be related to this issue as well. But basically dokku needs to be custom configured to have nginx headers to pass X-Forward-* headers. 
Which was my issue on another project. I am not around my setup to test it with Medusa server, but I suggest looking into dokku docs (around load balancing docs section)

**Comment by chemicalkosek** [comment]
@leikoilja Just bo clear, in Dokku it works for me without any issues when doing like this:

1. Create app in dokku
2. Deploy app with git
3. Add domain with `dokku domains:add <app> <domain>`
4. Add SSL with running `dokku letsencrypt:enable <app>`

That's it for me, never needed to modify nginx.

**Comment by 100tomtomas100** [comment]
I solved this issue by enabling Full (strict) SSL in cloudflare
