### ISSUE TITLE
Get cart from order using Admin API

### ISSUE THREAD

**Issue by benhammoush** [medusajs/medusa#2429]
Hi, 

In the Admin REST API reference i see we can return the cart object of an order using :

`import Medusa from "@medusajs/medusa-js"
const medusa = new Medusa({ baseUrl: MEDUSA_BACKEND_URL, maxRetries: 3 })
medusa.admin.orders.retrieve(order_id)
.then(({ order }) => {
  console.log(order);
});`

![image](https://user-images.githubusercontent.com/45472564/195346855-83d9a529-a9aa-4676-924a-817ab4c98fe6.png)

But in my case it only returns the cart ID.

Is it possible to get a cart using the cart ID from the Admin REST API ? 

Thanks.

**Comment by kasperkristensen** [comment]
Hi @benhammoush

It's not a bug, but you need to tell Medusa that you want to load the relation `cart`. You do so like this:

```js
medusaClient.admin.orders.retrieve(order_id, {
    expand: "cart",
  })
```

This was added recently so make sure that you are using the latest version of `@medusajs/medusa-js`

Closing this for now, but let us know if you need further assistance 😄

**Comment by Line255Bug** [comment]
is this an active issue?

**Comment by kasperkristensen** [comment]
@benhammoush I'll have to take my previous comment back. We actually don't allow expanding the cart relation on orders atm. We could easily add it, by adding `"cart"` to this array: https://github.com/medusajs/medusa/blob/4013c0c5da5952749eb109288b55fa7eec1f0537/packages/medusa/src/api/routes/admin/orders/index.ts#L344-L362

But what is your specific use case for this, all data that is part of the cart is available on the order, since the order is created from the cart. One concern with allowing users to freely expand every relation is that you quickly run into the issue where the SQL query gets so large that it will fail.

**Comment by benhammoush** [comment]
Hi, i want to get the context column of the cart table. 
Does adding cart to the array as you shown will work ?  

Thanks

**Comment by benhammoush** [comment]
Adding "cart" to both allowedAdminOrdersRelations  & defaultAdminOrdersRelations does the trick. 

Closing.

Thanks for your time.
