### ISSUE TITLE
UI templates and themes

### ISSUE THREAD

**Issue by paulpravosud** [medusajs/medusa#2466]
Hi guys! Thank you for the great product!
Can I ask you whether there are available themes and templates for the storefront like on templateforest.com or similar, where you can easily add them to Medusa store? If not, what are the current options in terms of designing a shop? Are there any frameworks or else that are compatible? And which ones that you would recommend to be the easiest to use? Thanks a lot in advance!
Rgds, Paul.

**Comment by kasperkristensen** [comment]
Hi @paulpravosud,

We have a couple of starters here on our GitHub that you can use to get started. Medusa is headless by design, and there are no themes or templates (the starters are just meant as a starting point), we leave the storefront implementation up to you. 

You can create a storefront with whatever framework you prefer. The starters we have are written in Next.JS and Gatsby, so it might be easier to create a storefront in a React or a React based framework, since you will then have something you can look to for inspiration. 

That being said there are multiple community projects written with React Native, Vue, Remix, etc., that are all public here on GitHub, that you could also take a look at. We also have a blog that you could browse, where there is a fair share of "Medusa Storefront implemented with X" posts - https://medusajs.com/blog/

**Comment by paulpravosud** [comment]
hi @kasperkristensen thanks a lot for help! Do you have your personal opinion on which of those to opt for at the first place (easiest)? Thanks a lot!

**Comment by kasperkristensen** [comment]
@paulpravosud I would properly go with something like Next, there's is a very large community around the framework, and lot's of articles, blogs, and videos that you can use as inspiration and guidance, while you are working on your first storefront 😄

**Comment by paulpravosud** [comment]
thanks a lot @kasperkristensen for valuable feedback on this!
