### ISSUE TITLE
Error in creating region, exactly in the countries property

### ISSUE THREAD

**Issue by RalphSaridar55** [medusajs/medusa#2634]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

whenever I try to create a region, it always fails because key countries has typeof  `Array<String>`

### How can this issue be resolved?

countries should be of type `Array<Object>`

such as: 
```
{
    "name": "region_created",
    "currency_code": "usd",
    "tax_rate": 10,
    "payment_providers": "manual",
    "fulfillment_providers":"manual",
    "countries": [
        {
        "id": 1,
        "value": "af",
        "iso_3": "afg",
        "num_code": 4,
        "name": "AFGHANISTAN",
        "label": "Afghanistan"
        }
    ]
}
```

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hi @RalphSaridar55 thank you for opening this issue. As mentioned in the [API reference](https://docs.medusajs.com/api/admin/#tag/Region/operation/PostRegions), countries is an array of the 3 character ISO code. So, instead of passing the entire object of a country, just pass the value in `iso_3`.

I'll close this issue for now. Let me know if you have any questions 🙂
