### ISSUE TITLE
medusa.products.search returns empty array but GET /store/products?q=foo works

### ISSUE THREAD

**Issue by finom** [medusajs/medusa#2735]
### Describe the bug

I've set up Medusa for the first time and I'm trying to implement search for seeded products. There is my NextJS code:

```js
import type { NextApiRequest, NextApiResponse } from 'next'
import Medusa from "@medusajs/medusa-js"

const MEDUSA_BACKEND_URL = 'https://medusa-foo.herokuapp.com/'

const medusa = new Medusa({ baseUrl: MEDUSA_BACKEND_URL, maxRetries: 3 })

type Data = {
  hits: unknown[];
}

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  
  const { hits } = await medusa.products.search({ // response is 200, I've checked
    q: 'Shirt'
  })

  res.status(200).json({ hits }); // hits is always []
}

```

But if I do it via REST API I get my list of products:

https://medusa-foo.herokuapp.com/store/products?q=Shirt

### System information

Medusa version (including plugins):
```json
"@medusajs/medusa": "^1.6.0",
"@medusajs/medusa-cli": "^1.3.3",
"medusa-fulfillment-manual": "^1.1.31",
"medusa-interfaces": "^1.3.3",
"medusa-payment-manual": "^1.0.16",
"medusa-payment-stripe": "^1.1.45",
"typeorm": "^0.2.36"
```
Node.js version: v19.0.1
Database: PSQL
Operating system: MacOS
Browser (if relevant): Not relevant

### Steps to reproduce the behavior

Try the code above.

### Expected behavior

I expect hits to be a non-empty array of products.

**Comment by chemicalkosek** [comment]
For the search to work, you need a search plugin installed like Algolia or MeiliSearch
https://docs.medusajs.com/add-plugins/meilisearch
https://docs.medusajs.com/add-plugins/algolia

The REST api works for you because you're not using `/products/search` `POST` endpoint but `/products` `GET` endpoint with some query attached.
You are getting all the products in the response, not products filtered by query.

**Comment by chemicalkosek** [comment]
For the search endpoint to work you need to add a search plugin like Algolia or Meili.
https://docs.medusajs.com/add-plugins/algolia
https://docs.medusajs.com/add-plugins/meilisearch

The REST endpoint works for you because you're using the `/products` `GET`, not `/products/search` `POST` endpoint.
https://docs.medusajs.com/api/store/#tag/Product/operation/GetProducts

To achieve the same on medusa js client you use:
```javascript
   const { products } = await medusa.products({
        q: 'Shirt',
      });
```

**Comment by chemicalkosek** [comment]
@finom Sorry, it's 
```javascript
const { products } = await medusa.products.list({
        q: 'Shirt',
      });
   ```
