### ISSUE TITLE
Cannot create customer after guest checkout

### ISSUE THREAD

**Issue by rrums123** [medusajs/medusa#2874]
## Bug report
After guest checkout, cannot create an account

### Describe the bug
Made a guest order, then try to create account for the email, got 422
```
{
    "code": "invalid_request_error",
    "type": "duplicate_error",
    "message": "Customer with email test.t0k9z4um@gmail.com already exists."
}
```

This scenario works well on v1.6.5

### System information

Medusa version (including plugins): 1.7.0
Node.js version: 16
Database: Postgres
Operating system: MacOS
Browser (if relevant): Postman

### Steps to reproduce the behavior

1. Checkout with email that has not account
2. Create account with same email (endpoint `POST store/customers`)

### Expected behavior

Able to create customer with the email

### Screenshots
<img width="480" alt="Screenshot 2022-12-22 at 4 20 18 PM" src="https://user-images.githubusercontent.com/100153954/209101274-fe31fa95-d133-46a1-a3e4-779112aee4e0.png">

<img width="720" alt="Screenshot 2022-12-22 at 4 19 05 PM" src="https://user-images.githubusercontent.com/100153954/209101012-769bfa3b-686b-46d4-b947-ac949abb96f9.png">

**Comment by olivermrbl** [comment]
@pKorsholm Would you mind assisting here?

**Comment by shahednasser** [comment]
Linking [this documentation](https://docs.medusajs.com/advanced/storefront/implement-claim-order#flow-overview) as well in case it's helpful 🙂

**Comment by pKorsholm** [comment]
have you run migrations after upgrading to version 1.7?

**Comment by pKorsholm** [comment]
you should be able to apply the latest migration with `medusa migrations run`

A bit of context around what I think the issue might be: 
We have changed the constraints around customers in the latest release in order to more gracefully handle registrations after guest checkouts. This means that we now allow two customer rows for each email in the database (one with a registered account and one without, indicated by the `has_account` property). However if you haven't applied migrations you will get a fail on the duplicate constraint since previously we only supported one row for each customer email.

In order for orders to be registered to the newly created customer, the documentation linked by @shahednasser [here](https://github.com/medusajs/medusa/issues/2874#issuecomment-1362605881) should provide an overview of the operation, otherwise feel free to ask @rrums123

**Comment by rrums123** [comment]
Yes, I can create customer after `medusa migrations run`, maybe this should be added on upgrade guides  https://docs.medusajs.com/advanced/backend/upgrade-guides/1-7-0

After customer creation, I see 2 accounts with same emails. The documentation about the claim order is clear so far. Thank you.

**Comment by shahednasser** [comment]
I'm already on it @rrums123 in PR #2875 , thanks for pointing it out! 😄
