### ISSUE TITLE
develop.sh not allowing medusa-server-default to run?

### ISSUE THREAD

**Issue by SHHSSH** [medusajs/medusa#2951]
### Describe the bug

I cannot figure out how to source, or what develop.sh is.

### System information

Medusa version (including plugins):
Node.js version: 19.2.0
Database: 
Operating system: Windows 11 22H2
Browser (if relevant):

### Screenshots

https://ibb.co/k2J9CPw
https://ibb.co/4Ybg8jP

**Comment by pKorsholm** [comment]
I'm unsure what you mean but here is a small description of `develop.sh`. If you have any follow up questions don't hesitate to ask 😄 

`develop.sh` is a bash script that runs migrations and starts the medusa server. It's not required in order to run your medusa server as you can always use `medusa start` or `medusa develop` to run your server. 

The script applies migrations before hand in order to ensure the database is updated.

(here)[https://github.com/medusajs/medusa-starter-default/blob/master/develop.sh] is a link to the file in the starter repository.
