### ISSUE TITLE
Inventory is not subtracted on placed order with enabled Manage Inventory

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/medusa#3240]
### Describe the bug

When _Manage Inventory_ is enabled, variant inventory is not subtracted when order is placed. 
This was reported by user on Discord, I have tested and indeed the issue exists. I would consider this quite critical.
User also reported that returning an item does increase the inventory count.

### System information

Medusa version (including plugins): 1.7.6 (happens on 1.7.5 too)
Node.js version: 18.14
Database: postgres

### Expected behavior

Inventory is subtracted when order is placed.

**Comment by olivermrbl** [comment]
This is likely due to carts being completed without using the cart-completion strategy, which contains the inventory adjustment step. E.g. if the `OrderService.createFromCart` is used directly, you will need tax lines creation, payment authorization, and inventory adjustment as preliminary steps.

I realise, the Stripe webhook endpoint does not currently handle this, so this might be the culprit to your issue. I've added it to our backlog and we will investigate asap :)

**Comment by olivermrbl** [comment]
@chemicalkosek Can I get you to confirm that this is only when orders are created through the Stripe webhook? We will solve the webhook issue in #3257, so I am closing this to avoid confusion around our inventory management functionality.

**Comment by chemicalkosek** [comment]
Confirmed :) I saw the PR using cart completion strategy for webhook. Should definitely fix this.
