### ISSUE TITLE
Updating a Cart via context but not metadata does not make sense?!

### ISSUE THREAD

**Issue by OD91** [medusajs/medusa#3307]
I would like to add kind of metadata to the Cart (at checkout) such as "optional comments on the delivery", "optional ERP order number from the B2B customer", etc. - but; although a Cart has a `metadata` field in its response I can't update the `metadata` field directly but have to update via `context` as it seems. This does not make that much sense to me. Link to the doc I refer to is here: https://docs.medusajs.com/api/store/#tag/Cart/operation/PostCartsCart

Currently it seems, if I wanna update the Cart I would do this best by just adding it to the `metadata` of the `billing_address` or `shipping_address`?! Seems wrong place to me, thus I would like to add it to the `metadata` field of the Cart...

**Comment by josetr** [comment]
I think it would be interesting to know what's the exact role of `context` is. Right now the server stores both the `user_agent` and `ip` when the cart is created, but it also allows you to overwrite it, so it's hard to rely on the IP since it can be faked really easily.

Maybe it would make more sense to change `{ ...reqContext, ...validated.context }` to `{ ...validated.context, ...reqContext }`, or perhaps add an `ip` field to the `Cart` entity / database.

As for the `metadata`, it should be fairly easy to add it by making the necessary changes in both

https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/carts/create-cart.ts and 
https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/carts/update-cart.ts

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Comment by t-lock** [comment]
@sradevski I just came across this, I have the same use case, need to add metadata to my cart from the storefront, but this does not seem possible. Can you confirm/deny that Medusa V1 does not provide any means of updating cart metadata from the storefront?
