### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by C2EN** [medusajs/medusa#3358]
#### Bug appears on Android 【SyntaxError: Unexpected token '?'】
userAgent: Mozilla/5.0 (Linux; Android 10; V1924A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.96 Mobile Safari/537.36

![image](https://user-images.githubusercontent.com/34909064/222391850-7af7c16b-c5d0-4fa7-8713-b5b32e85f601.png)
![image](https://user-images.githubusercontent.com/34909064/222393657-e1a9f6de-bc44-4162-baf7-892e33a21cf9.png)

The bug code is on the 【medusa/packages/medusa-js/src/request.ts  174&175 line】
<img width="385" alt="image" src="https://user-images.githubusercontent.com/34909064/222467440-851194fb-9f9f-4a89-8393-40b030ea9123.png">

**Comment by kasperkristensen** [comment]
Hi @C2GitHub,

Not a bug but due to nullish coalescing not being supported by some [older browsers](https://caniuse.com/?search=nullish%20coalescing). 

We would be happy to accept a PR that switches out the usage to Logical OR (`||`), but that is also not supported by [all versions of Android browsers](https://caniuse.com/mdn-javascript_operators_logical_or) so may not help in your case.
