### ISSUE TITLE
Updated claim page does not function

### ISSUE THREAD

**Issue by magdafiktus** [medusajs/medusa#3361]
**Describe the bug**
We cannot create claims on one item on the order without issuing a refund. 
Also, SKU's are missing. 
Also, we replace items way more often than we issue refunds for claims. Could these two buttons be switched back around so that "Replace" is the preselected option? (text in the picture should be saying "Preselected" - not reselected")

    "@medusajs/medusa": "^1.7.9",
    "@medusajs/medusa-cli": "^1.3.8",
    "babel-preset-medusa-package": "1.1.19",
    "contentful": "^7.14.7",
    "cors": "^2.8.5",
    "cross-env": "^7.0.2",
    "csv-stringify": "5.3.2",
    "easy-soap-request": "^3.3.3",
    "express": "^4.17.1",
    "joi": "^17.3.0",
    "medusa-core-utils": "^1.1.39",
    "medusa-file-spaces": "1.3.5",
    "medusa-fulfillment-manual": "1.1.36",
    "medusa-fulfillment-webshipper": "^1.3.7",
    "medusa-interfaces": "1.3.6",
    "medusa-payment-adyen": "1.1.43",
    "medusa-payment-klarna": "1.3.8",
    "medusa-payment-paypal": "1.2.10",
    "medusa-payment-stripe": "1.1.53",
    "medusa-plugin-brightpearl": "1.3.6",
    "medusa-plugin-contentful": "^1.2.7",
    "medusa-plugin-discount-generator": "1.1.24",
    "medusa-plugin-ip-lookup": "1.2.5",
    "medusa-plugin-meilisearch": "1.0.4",
    "medusa-plugin-restock-notification": "2.0.4",
    "medusa-plugin-segment": "^1.3.4",
    "medusa-plugin-sendgrid": "1.3.7",
    "medusa-plugin-sentry": "^1.4.1",
    "medusa-plugin-slack-notification": "1.3.8",
    "medusa-plugin-wishlist": "1.1.41",
    "medusa-test-utils": "1.1.37",
    "mongodb": "^3.6.3",
    "mongoose": "^5.10.14",
    "pdfkit": "^0.11.0",
    "tmp": "^0.2.1",
    "typeorm": "^0.2.31",
    "xml2js": "^0.4.23"

Steps to reproduce the behavior

1. try to make a claim on one item

Screenshots
![Skærmbillede 2023-03-02 kl  12 37 52](https://user-images.githubusercontent.com/116171296/222433208-ac6613f1-72ab-45d1-8e92-4fd6b0b0058e.png)
![Skærmbillede 2023-03-02 kl  12 41 37](https://user-images.githubusercontent.com/116171296/222433210-bf1556ad-ac82-4cef-bd2e-fab2eaa5676a.png)

**Comment by kasperkristensen** [comment]
Hi @magdafiktus 

The refund amount shown is what the default refund amount for the claim is. Claims in Medusa will refund the full amount for the claimed items per default, but as described if you hover over the orange exclamation mark, you have the option to specify a custom refund amount upon receiving the return. 

![image](https://user-images.githubusercontent.com/45367945/222453837-fd6512c4-bcb4-4bfc-b717-c53487a70a96.png)

When there is a return order on a "replace" claim, the refund is only issued once the item;s are returned, so you can safely create the claim, and then specify a custom refund amount once you receive the items.

![image](https://user-images.githubusercontent.com/45367945/222454587-6830d5df-25cf-4841-a8c6-6f5df613c335.png)

Hope that explains it, otherwise, let me know and I'll be happy to answer any questions you might have. 

And I will open an issue for adding SKU's to the table views in our admin repository 😄

**Comment by KatrineStub** [comment]
Hi @kasperkristensen 

Thank you for your reply. 

When creating a claim and replacing a defective item, we will never issue a refund. For us, the refund amount on claims where we replace the item is causing unnecessary confusion. Could this amount be preset to 0 so that we will not issue any refund by accident?

**Comment by magdafiktus** [comment]
Hey, this is still an issue, please reopen.
