### ISSUE TITLE
Postgres transaction errors

### ISSUE THREAD

**Issue by nekszt** [medusajs/medusa#3516]
Hi

### Describe the bug

I open this issue with few chances to have it solved in few weeks, except it was already identified or there is an incompatibility with some versions or version issues.

**I've always had many postgres transaction errors in dev or prod in various cases.**

I have already noticed that when 2 actions are done, concurrently or sequentially in a short time, this error pops. Failed transactions are not handle ? Bad isolation level ?

The most serious consequences are that some orders are not created after successful payment... Customers retry -> refund needed
It will become critical with higher traffic.

### System information

Medusa version (including plugins): 1.7.5
Node.js version: 17.1.0
Database: postgres 10.4

### Steps to reproduce the behavior

I don't know how to reproduce this error. Maybe we can try to send multiple actions in a short time.

### Expected behavior

Retry mechanism if a transaction fails

### Screenshots

![Screenshot from 2023-03-17 15-17-33](https://user-images.githubusercontent.com/10143046/225931053-f195221a-f4f4-4272-be67-6f00cf873900.png)

**Comment by adrien2p** [comment]
Can you tell us which payment plugin are you using? 

In the context of a serializable transaction, this is something that happens frequently as it enforces the data state to not change, and the retry mechanism you be automatically manged when a 409 is returned, using the idempotency key. You can read more on that subject on the Postgres documentation itself.

If you are using stripe, this happens when both the API try to complete while stripe send a web hook which trigger the completion as well. In that case, you can find some resolved discussion on that topic on how to handle it properly without having to disable the webhook.

**Comment by nekszt** [comment]
I'm using Stripe payment plugin. I don't know well the code in that plugin.
I also have this kind of error when my fulfillment provider sends bunch of requests on an endpoint I created (mark orders as shipped).

So, retry mechanism is not implemented in Medusa core? REST API users and plugin developers have to implement it?

**Comment by adrien2p** [comment]
yes exactly, it is part of our client library, if you get a 409 it will retry it with the idempotency key but for custom usage you need to handle it on your side
