### ISSUE TITLE
/admin/product-categories/:categoryId?expand=products does not expand products

### ISSUE THREAD

**Issue by Arsenalist** [medusajs/medusa#3788]
[The docs](https://docs.medusajs.com/api/admin#tag/Product-Categories/operation/PostProductCategories) say this should return the products in a category

However, [looking at the code 1.8](https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/api/routes/admin/product-categories/get-product-category.ts) it doesn't consider the `expand` field. 

Sending an `expand=products` query parameter results in the following response:

```
{
    "type": "invalid_data",
    "message": "Relations [products] are not valid"
}
```

**Comment by olivermrbl** [comment]
@riqwan – will you assist @Arsenalist? 

I believe we do not allow you to expand products as of now, but maybe it is worth considering supporting it.

**Comment by riqwan** [comment]
Thanks for pointing this out @Arsenalist . Looks like I made a mistake in the documentation. We don't currently support it, you can query `store/products?category_id[]=category_id` to get all the products for a category. 

Since a category can potentially have 100s of products attached to it, expanding products via the category endpoint will slow down the endpoint (without pagination), especially if you're passing in include_descendants_tree=true. This is why we've kept it out from the endpoint so far.

**Comment by olivermrbl** [comment]
@Arsenalist – Given @riqwan's comment, I categorize this as a feature request. Therefore, please move it to GitHub Discussions if the alternative solution provided is insufficient for your use case.
