### ISSUE TITLE
S3 plugin error: [CredentialsError]: on v1.1.12

### ISSUE THREAD

**Issue by imash96** [medusajs/medusa#3830]
### Describe the bug

S3 plugin throws this error when trying to upload a product image on v1.1.12 npm:

### System information

Medusa version (including plugins):
Node.js version: 18
Database: postgres
Operating system: win11
Browser (if relevant): chrome

### Expected behavior

I have installed medusa backend using npm and also installed medusa-file-s3 plugin via npm which install v1.1.12
so when I try to upload product images it gives below error
Error [CredentialsError]: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

after a lot of try and test I uninstall v1.1.12 and installed medusa-file-s3 v1.1.11 via this command "npm i medusa-file-s3@1.1.11 --force"
I have not changed .env file and medusa-config.js and product got uploaded successfully, so basically there is a bug in v1.1.12

**Comment by pevey** [comment]
This issue will be fixed with a pending pull request:  https://github.com/medusajs/medusa/pull/3740.  

In the meantime, there is a workaround, and it is also considered best security practice rather than hardcoding your credentials.

You can follow this guide to install the AWS CLI and enter your credentials via the command line on the machine where medusa is running.  https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

If that machine is a linux server, here are the relevant bits:

```
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
aws configure
```

**Comment by imash96** [comment]
When will the update push 🥺🥺

**Comment by imash96** [comment]
When will the update push to npm🥺🥺

**Comment by olivermrbl** [comment]
#3740 merged. Patch releasing early next week :)

**Comment by tunchunairarko** [comment]
At the time of writing, unless an AWS config file is set either via aws cli or manually (.aws/config) the package `medusa-plugin-s3` only works if `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables are set. These two variables can be set either inside the .env file or by sourcing into the shell.
