### ISSUE TITLE
unable to build client types

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#3919]
### Describe the bug

@medusajs/client-types:build: [Error: EACCES: permission denied, mkdtemp '/tmprW9Coc'] {
@medusajs/client-types:build:   errno: -13,
@medusajs/client-types:build:   code: 'EACCES',
@medusajs/client-types:build:   syscall: 'mkdtemp',
@medusajs/client-types:build:   path: '/tmprW9Coc'
@medusajs/client-types:build: }
@medusajs/client-types:build: ERROR: command finished with error: command (/home/

yarn run build after merging develop into an existing medusa monorepo

### System information

Medusa version (including plugins): 1.8.2
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior
yarn run build after merging develop into an existing medusa monorepo

### Expected behavior

No errors in the build

**Comment by pevey** [comment]
I get this error also when working with the monorepo on my local machine. The build steps are set up for a different type of system. There are 2 places (if I remember correctly) where I had to comment out the function used to generate the temp file directory and instead just specify ‘/tmp’ It has to be somewhere your basic user account has permission to write. The nuclear option is to use sudo, but of course not recommended.

**Comment by SGFGOV** [comment]
Yeah that is a nice work around but it's easier if the code just remained os and environment agnostic

**Comment by pevey** [comment]
I have some time this morning, I'll work on a PR

**Comment by pevey** [comment]
After looking into a bit, this is what I've learned so far:

- Github actions make available a temp directory that is created for each job and cleared at end.  It can be accessed using the env var RUNNER_TEMP.  (https://docs.github.com/en/actions/learn-github-actions/variables)

- In 2 places, the repo build is set to use the RUNNER_TEMP value if it is set, otherwise it uses the built in node function os.tmpdir().

1. In  packages/generated/client-types/scripts/build.ts, line 9
2. In packages/oas/medusa-oas-cli/src/utils/fs-utils.ts, line  27

- It looks this SHOULD result in a valid temp directory, but it's not working.

1) [deleted] EDIT: I think this might not be an issue and was an indirect result of bullet 2) because of the way I was trying to log these values. Thought of some more things I can try in a few minutes when I get back home. 
2) The usage of  fs.mkdtemp is a bit off, so the getTmpDirectory function is only returning the randomly generated string that is intended to be the subdirectory, not the full path that should be returned for it to work properly.

Will do some more reading, but I'm thinking the best solution for now might be to manually path.join 'tmp' and the randomly-generated string.  Should work for the CI and for people on linux and macs.  Will probably still cause problems for people using Windows, but no worse than now.

**Comment by pevey** [comment]
You can ignore all the TLDR above.

**Basically, it needs the separator.  Will do some more testing, and then prepare the PR.**

The root issue is described here: https://nodejs.org/docs/latest-v9.x/api/fs.html#fs_fs_mkdtemp_prefix_options_callback

```// The parent directory for the new temporary directory
const tmpDir = os.tmpdir();

// This method is *INCORRECT*:
fs.mkdtemp(tmpDir, (err, folder) => {
  if (err) throw err;
  console.log(folder);
  // Will print something similar to `/tmpabc123`.
  // Note that a new temporary directory is created
  // at the file system root rather than *within*
  // the /tmp directory.
});

// This method is *CORRECT*:
const { sep } = require('path');
fs.mkdtemp(`${tmpDir}${sep}`, (err, folder) => {
  if (err) throw err;
  console.log(folder);
  // Will print something similar to `/tmp/abc123`.
  // A new temporary directory is created within
  // the /tmp directory.
});
```

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
