### ISSUE TITLE
product-type endpoints not returning metadata field

### ISSUE THREAD

**Issue by DhifMlak** [medusajs/medusa#3952]
Hello Medusers !

The  **/store/product-types** and **/admin/product-types**  endpoints returns the list of  product types but without the metadata field

**Description :**

In both endpoints , the **metadata** filed is missing in the **allowedStoreProductTypeFields**  , **defaultStoreProductTypeFields**  and **defaultAdminProductTypeFields** 

```
export const allowedStoreProductTypeFields = [
  "id",
  "value",
  "created_at",
  "updated_at",
]
```

```
export const defaultStoreProductTypeFields = [
  "id",
  "value",
  "created_at",
  "updated_at",
]
```
```
export const defaultAdminProductTypeFields = [
  "id",
  "value",
  "created_at",
  "updated_at",
]
```

**Comment by olivermrbl** [comment]
Thanks for submitting the PR. We might need to tweak a couple of tests to turn the CI green, but we'll see :)

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
