### ISSUE TITLE
`silentResolution` function leads to lots of head scratching 🤯

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#4022]
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/12628251/236317600-f8ec5ad7-740e-4efd-aa6d-1c563a8c91d0.png">

I assume there was a good reason Medusa needed to swallow `AwilixResolutionError`s here at some point, but is there still a need for it? 

I spent a good hour trying to figure out why all my registered fulfillmentProviders disappeared whenever I added a plugin I created. Looks like I had a bad file name that was causing a resolution error in a fulfillment provider, which caused this function to return [] silently. I would have figured that out an hour sooner if those errors didn't get swallowed into the abyss haha :)

**Comment by olivermrbl** [comment]
Sorry to hear this caused you headaches. I would be fine with writing the entire error to the log. Would you be up for opening a PR with the changes? :)

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
