### ISSUE TITLE
Error when doing yarn build for local development of backend

### ISSUE THREAD

**Issue by nikhil-1911** [medusajs/medusa#4029]
![image](https://user-images.githubusercontent.com/131291664/236603701-d0baa31b-0c6b-41f2-a017-6a41b1843861.png)
I get this error and causes yarn build command to fail for local development of backend.
I forked the repository and cloned develop branch.

**Comment by pevey** [comment]
Interesting.  I do not get that error, but I use a linux (ubuntu) environment.  Curious if that difference might point to a possible cause.  Appears from above that you a in a Windows environment.

**Comment by sats268842** [comment]
It might be a Windows issue because the error occurred when I used Windows to generate Open API Docs, but it didn't when I tried the procedure in Ubuntu. As to my observations, the package is not detecting the oas comments in the api folder. So it will throw an error when validating OAs generated file.

**Comment by nikhil-1911** [comment]
> Interesting. I do not get that error, but I use a linux (ubuntu) environment. Curious if that difference might point to a possible cause. Appears from above that you a in a Windows environment.

Yes I am in Windows 11

**Comment by nikhil-1911** [comment]
> It might be a Windows issue because the error occurred when I used Windows to generate Open API Docs, but it didn't when I tried the procedure in Ubuntu. As to my observations, the package is not detecting the oas comments in the api folder. So it will throw an error when validating OAs generated file.

Can you suggest a possible workaround for this?

**Comment by nikhil-1911** [comment]
@olivermrbl Can you suggest a fix, I am using Windows 11 Pro

**Comment by nikhil-1911** [comment]
> Interesting. I do not get that error, but I use a linux (ubuntu) environment. Curious if that difference might point to a possible cause. Appears from above that you a in a Windows environment.

Should I change to linux

**Comment by pevey** [comment]
I'm pretty sure I've built in the past on Windows without this error, but maybe it has to do with your node version?  or it could be an issue that has popped up fairly recently.

In any case, have you looked into WSL?  Installing Ubuntu on Windows via WSL would allow you to have a fully *nix dev environment without too much hassle.

https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
