### ISSUE TITLE
medusa-source-shopify CustomRepositoryNotFoundError: Custom repository  was not found. 

### ISSUE THREAD

**Issue by felixelement** [medusajs/medusa#4086]
### System information

Medusa version (including plugins):
```
    "@medusajs/medusa": "^1.10.1",
    "@medusajs/medusa-cli": "^1.3.12",
"medusa-source-shopify": "^1.2.8",
```
Node.js version: 18.13.0
Database: sqlite default
Operating system: Mac OS venture v13.0
Browser (if relevant):

### Steps to reproduce the behavior

1. setup quick medusa app starter 
2. add medusa-source-shopify plugin. add SHOPIFY_STORE_URL to env file (abc.myshopify.com --> added `abc`). password to env file with `admin api access token ` after installing app on shopify store.
3. `yarn start`
4. got error:
```
CustomRepositoryNotFoundError: Custom repository  was not found. Did you forgot to put @EntityRepository decorator on it?
    at EntityManager.getCustomRepository (/Users/felixle/Downloads/6github_new/e6apparel-back-end/node_modules/typeorm/entity-manager/EntityManager.js:790:19)
    at _callee3$ (/Users/felixle/Downloads/6github_new/e6apparel-back-end/node_modules/medusa-source-shopify-json/services/shopify-collection.js:193:59)
    at tryCatch (/Users/felixle/Downloads/6github_new/e6apparel-back-end/node_modules/medusa-source-shopify-json/services/shopify-collection.js:11:1360)
    at Generator.<anonymous> (/Users/felixle/Downloads/6github_new/e6apparel-back-end/node_modules/medusa-source-shopify-json/services/shopify-collection.js:11:4177)
    at Generator.next (/Users/felixle/Downloads/6github_new/e6apparel-back-end/node_modules/medusa-source-shopify-json/services/shopify-collection.js:11:2211)
    at asyncGeneratorStep (/Users/felixle/Downloads/6github_new/e6apparel-back-end/node_modules/medusa-source-shopify-json/services/shopify-collection.js:15:103)
    at _next (/Users/felixle/Downloads/6github_new/e6apparel-back-end/node_modules/medusa-source-shopify-json/services/shopify-collection.js:16:194)
    at /Users/felixle/Downloads/6github_new/e6apparel-back-end/node_modules/medusa-source-shopify-json/services/shopify-collection.js:16:364
    at new Promise (<anonymous>)
✔ Plugins intialized – 8432ms
```
 

### Expected behavior

sync data from shopify and medusa app

### Screenshots

![1](https://github.com/medusajs/medusa/assets/126806286/2735a1e0-ada2-4c0c-a848-a1aeab087204)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

I just started it with the default starter. So please check

**Comment by felixelement** [comment]
I also tested with Postgres db. but I got the same issue

**Comment by keyboSlice** [comment]
I've hit this same error, from a clean setup - did you manage to resolve it at all?

**Comment by felixelement** [comment]
nope, as we cannot touch on its source codes, we cannot fix this issue. I format again the data you can check here: https://stackoverflow.com/questions/76195203/medusajs-with-strapi-default-command-run-error-applicationerror-the-type-is-r

**Comment by devowloper** [comment]
@olivermrbl this particular issue, whilst relatively straightforward to workaround, inhibits the velocity of trialing Medusa with Shopify data. May you spare the resources to look into this bug?

**Comment by coopbri** [comment]
Ran into the same issue today. Related Discord discussion: https://discord.com/channels/876835651130097704/1096377017781469275/1214513798942035968

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Comment by zohfur** [comment]
This plugin is still the recommended way to migrate from Shopify to Medusa but it is currently still broken. This issue was never fixed and it seems like there is currently no way to migrate anything from a Shopify store automatically. I understand this might only apply to v1, but as of right now this is still an issue. Can we get any kind of suggested fix or patch on this? Otherwise the NPM module and docs should be updated to reflect this package is deprecated.

I've tried to onboard onto Medusa for the past two days thinking it would take me "less than 10 minutes" but so far this has been a huge headache.

https://docs.medusajs.com/plugins/source/shopify
https://dev.to/medusajs/turn-a-shopify-backend-open-source-and-headless-in-less-than-10-minutes-2g8m
https://www.npmjs.com/package/medusa-source-shopify
![image](https://github.com/user-attachments/assets/12a9020b-3714-421d-85de-86fdf7a6a184)
