### ISSUE TITLE
Error Creating Medusa Client in Existing Node JS Project

### ISSUE THREAD

**Issue by yash-madaan** [medusajs/medusa#4104]
Hi Team, I have some query related to medusa client.
So I have installed the medusa client in my existing node js (commonjs) project. While Importing the client and getting any object of client using constructor, I am facing one error:

//Import Statement:
const Medusa = require('@Medusajs/medusa-js');
//Usage: 
      const client = new Medusa({
        baseUrl: process.env.MEDUSA_BACKEND_URL,
        maxRetries: 3,
      });

Error:
TypeError: Medusa is not a constructor

And if i use import statement as per doc: 
import Medusa from '@medusajs/medusa-js';

it gives an error: Cannot use import statement outside a module

**Comment by cellis** [comment]
Also get this error while trying to use `withCustomWebpackConfig`

```3:02:37 PM [@medusajs/admin] An error occured while trying to load your custom Webpack config. See the error below for details:
/Users/cameronellis/work/store-server/src/admin/webpack.config.js:1
import { withCustomWebpackConfig } from "@medusajs/admin"
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
