### ISSUE TITLE
Localhost blocking cookie setting from domain api

### ISSUE THREAD

**Issue by Anuro0p** [medusajs/medusa#4123]
### Describe the bug

The set-cookie header in Apis is not working in local host due to Check Same-Site Attribute For development purposes we need to set it to SameSite=None (along with the Secure attribute set to false) to allow the cookie to be sent in cross-site requests. And the Api is throwing a 401 error code.

### System information

Medusa version (including plugins): 1.11.0
Node.js version: 18.0.0
Database: Postgres
Operating system: Windows
Browser (if relevant): Chrome

### Screenshots

![issue-23332](https://github.com/medusajs/medusa/assets/82078482/7d9fb578-7780-4131-9cc1-7c13c10ca53f)

**Comment by pevey** [comment]
It would be pretty straightforward to expose these as part of the session options in https://github.com/medusajs/medusa/blob/a91987fab33745f9864eab21bd1c27e8e3e24571/packages/medusa/src/loaders/express.ts.  But I'm not sure it's a good idea.  I know there was recently an extensive PR related to auth and specifically to bearer auth.  That would probably be a better approach for this use case than changing the cookie settings.

I can do a quick PR to expose the session opts if the team wants to go that route.

EDIT:  In the meantime, you can make the changes directly in the compiled file in your node_modules folder as a workaround.

**Comment by Anuro0p** [comment]
It worked Thanks!

**Comment by Simon-Bertrand** [comment]
> It would be pretty straightforward to expose these as part of the session options in https://github.com/medusajs/medusa/blob/a91987fab33745f9864eab21bd1c27e8e3e24571/packages/medusa/src/loaders/express.ts. But I'm not sure it's a good idea. I know there was recently an extensive PR related to auth and specifically to bearer auth. That would probably be a better approach for this use case than changing the cookie settings.
> 
> I can do a quick PR to expose the session opts if the team wants to go that route.
> 
> EDIT: In the meantime, you can make the changes directly in the compiled file in your node_modules folder as a workaround.

Would be really nice if we just could be able to add the Domain property of a cookie in the sessionOpts of the session object of the library express-session.

I believe Set-Cookie response header of an auth request will also work for subdomains. In my case, the medusa backend is proxied as a subdomain (api.domain.com), where the Set-Cookie response header is not setted by the browser because of the different origin. The workaround I did is to serve the medusa backend as domain.com/api which is suitable for the api but not for the admin panel (which is on admin.domain.com).

Would be cool if we can customize a bit those express-session parameters without having to modify the compiled medusa express loader.

**Comment by redjor** [comment]
I have the same issue, and for now, I didn't find a solution instead of modify the session through the express loader and I don't really want to do that. If anyone as a workaround?
