### ISSUE TITLE
bug with variants when duplicate products

### ISSUE THREAD

**Issue by giovihh** [medusajs/medusa#4177]
bug with variants when duplicate products... 

## Bug report

https://streamable.com/ad6fml

### System information

Medusa version (including plugins):
Node.js version: Latest
Database: PostGreSQL latest
Operating system: W11 pro 22h2
Browser (if relevant): Chrome

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
