### ISSUE TITLE
sendGridService.sendEmail not sending data object to sendgrid.

### ISSUE THREAD

**Issue by thephpguy** [medusajs/medusa#4373]
When attempting to send an email using the sendgrid service method "sendEmail" the data object is not sent to sendgrid.

Here is some example code:
```
this.sendGridService.sendEmail({
      templateId: this.sendGridService.options_.send_invite,
      from:  this.sendGridService.options_.from,
      to: data.user_email,
      data: {
        token: data.token,
      },
    })
```

In the above code the email is sent however the data object containing the token is not sent to sendgrid.

` "medusa-plugin-sendgrid": "^1.3.7",`

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
