### ISSUE TITLE
medusaClient.carts.retrieve - items are returned without metadata

### ISSUE THREAD

**Issue by ensidialabs** [medusajs/medusa#4390]
### Describe the bug
Previously when using medusaClient.carts.retrieve(id).then(({ cart }) => cart)
items which returned the metadata of the products in the cart, and now it is empty. Updated from version 10 to the latest and the metadata disappeared (it is present in the products)

### System information

Medusa version (including plugins): 1.12.1

**Comment by huotarih** [comment]
I have the same for orders.

**Comment by fxmb** [comment]
Having the same issue, considering to additionally fetch the metadat via the `product_id` provided by the `LineItem` object

**Comment by huotarih** [comment]
> Having the same issue, considering to additionally fetch the metadat via the `product_id` provided by the `LineItem` object

If you're fetching a whole order, you can use `        const order = await this.orderService_.retrieve(data.id, { relations: ["items","items.variant", "shipping_methods", "shipping_address"] });
`

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
