### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by johnsmithodom** [medusajs/medusa#4412]
### System information

Medusa version (including plugins): 1.3.16 
Node.js version: v20.3.1
Database: postgresql
Operating system: Distributor ID: Debian Description:    Debian GNU/Linux 11 (bullseye) Release:        11 Codename:       bullseye
Browser (if relevant): firfox

### Steps to reproduce the behavior
fresh install follow the guide with backed and fronted installed 
1. Go to 'ip:8000'

Unhandled Runtime Error

Error: Network Error
Call Stack
createError
node_modules/@medusajs/medusa-js/node_modules/axios/lib/core/createError.js (16:0)
handleError
node_modules/@medusajs/medusa-js/node_modules/axios/lib/adapters/xhr.js (117:0)

![image](https://github.com/medusajs/medusa/assets/120798996/2fb20231-aad5-4742-befb-bd996ea41c88)

### Expected behavior

No error at all for the fresh installed since nothing has been modified from source code.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by kasperkristensen** [comment]
@johnsmithodom Please provide more information. Are you seeing an error in your server logs, is your server even running (if not then the error you are seeing will happen because all requests will fail), is your server running on port 9000, if not did you change the port over in the Next starter, etc.

**Comment by johnsmithodom** [comment]
![image](https://github.com/medusajs/medusa/assets/120798996/531c147e-81ae-4338-b5c1-04d07d70b41d)


I "think" the vps doesn't have enough ram. not sure. (since can't fine any hardware requirement for medusajs)

**Comment by shurerider** [comment]
Did you end up figuring this out for sure? I'm running into the same issue.

**Comment by milan-lakhani** [comment]
https://docs.medusajs.com/development/backend/configurations#:~:text=The%20Medusa%20backend's%20endpoints%20are,requests%20to%20the%20backend's%20endpoints.

This helped me resolve the issue

**Comment by oscardobsonbrown** [comment]
I just started having the same issue after creating some products and restarting the front and back ends

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
