### ISSUE TITLE
Disabling Telemetry

### ISSUE THREAD

**Issue by pevey** [medusajs/medusa#4423]
Even with these environment variables set as described here: https://docs.medusajs.com/usage:

```
MEDUSA_DISABLE_TELEMETRY=true
MEDUSA_FF_ANALYTICS=false
```

The admin is still making network calls to segment.com.

**Comment by jporsay** [comment]
Faced this issue while working on the road, which was unfortunate :(

Seems like this bug is coming from this global instantiation of `AnalyticsBrowser`:

https://github.com/medusajs/medusa/blob/17c26c4f66c50b94edec44743186f44e0f2aa7d2/packages/admin-ui/ui/src/services/analytics.ts#L19

I've created a PR to try and address it.
