### ISSUE TITLE
medusa-plugin-mailchimp npm package is wrong - backend crashes

### ISSUE THREAD

**Issue by RegisWeduLabs** [medusajs/medusa#4435]
### Describe the bug

The npm package for version 1.1.50 is not complete.  There aren't any relevant files.  See link below.
https://www.npmjs.com/package/medusa-plugin-mailchimp/v/1.1.50?activeTab=code

When trying to resolve mailchimpService the backend crashes.

### Expected behavior
The package should look like this:
https://www.npmjs.com/package/medusa-plugin-mailchimp/v/1.1.50-beta-20230619170349?activeTab=code

This one works - but not ideal as it is still in beta...

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
