### ISSUE TITLE
Metadata not in response when using medusa-react

### ISSUE THREAD

**Issue by oliwerhelsen** [medusajs/medusa#4436]
## Bug report
When requesting my collections i'm not getting the metadata property of my collection.

### Describe the bug
I'm requesting all my collections with the useAdminCollections hook.

### System information

Medusa version (including plugins):
Node.js version: v18.12.1
Database: Postgres
Operating system: MacOsx

### Steps to reproduce the behavior
Just using the useAdminCollections.

### Expected behavior

Expecting metadata to be provided

### Screenshots

<img width="116" alt="bild" src="https://github.com/medusajs/medusa/assets/2570700/54cda7c1-47d4-4754-b95c-872bf704f93f">

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
