### ISSUE TITLE
 Serverless Product Module does not return the price of the product.

### ISSUE THREAD

**Issue by ensidialabs** [medusajs/medusa#4448]
### Describe the bug

```
import { NextResponse } from "next/server"

import { 
  initialize as initializeProductModule,
} from "@medusajs/product"

export async function GET(request: Request) {
  const productService = await initializeProductModule()

  const data = await productService.list()

  return NextResponse.json({ products: data })
}
```

Returns the product, returns the variant, but there is no price in the variant. Why?
Tried adding relations: ["variants"], but still no price.

### System information

Medusa version (including plugins): latest

**Comment by tsvetann** [comment]
Maybe because you haven't passed the region and currency to your query?

**Comment by ensidialabs** [comment]
> Maybe because you haven't passed the region and currency to your query?

Thanks ill try do this.

**Comment by ensidialabs** [comment]
Tried it. productService.list() does not know anything about region and currency and gives an error.

**Comment by tsvetann** [comment]
> Tried it. productService.list() does not know anything about region and currency and gives an error.

you have to show some code, otherwise I am afraid I am unable to help any further

**Comment by riqwan** [comment]
Hey @ensidialabs, the Products Module is still in beta release phase and pricing hasn't been tackled yet. We are currently working on it and since this is still experimental, we unfortunately don't have a solid timeframe to give you yet.

**Comment by adrien2p** [comment]
@ensidialabs just to add some info, the product module is not supposed to know anything about the prices. It just provides the product feature. The prices will be part of a separate module that runs in isolation like the inventory and stock location do. We will introduce new concepts in the future in order to link multiple modules together and to be able to have a single entry point to query them and in return get the aggregated data from the different modules. We will provide that information in time in the future.

**Comment by adrien2p** [comment]
In the meantime, the only way to attach the prices to the products is to do it in a separate step like [here](https://github.com/medusajs/product-module-demo/blame/ecc6090913ad4d61adbb7964321082151aa7fab3/src/app/api/products/route.ts#L67) for example.

**Comment by ensidialabs** [comment]
Understood. Thanks a lot for the clarification. I look forward to new features and development 
❤️ MedusaJs
