### ISSUE TITLE
Retrieve By Handle is Case Sensitive

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#4565]
## Bug report
Retrieving collections by the handle is case sensitive
### Describe the bug
Typically handles aren't meant to be case-sensitive as they are often used as a part of the URL 
Is this by design?

**Comment by adrien2p** [comment]
i suppose we should change the validator, since the buildQuery support `contains`. wdyt @olivermrbl

**Comment by olivermrbl** [comment]
One could also make the case that we should lower-case handles on DB insertion and normalize them when querying. But this would be a change of convention; all handles should be treated similarly.

**Comment by olivermrbl** [comment]
Yes, changing the validator seems reasonable.

@SGFGOV, that would allow you to query collections like so:
```
GET /store/collections?handle[contains]=some_handle
```

**Comment by SGFGOV** [comment]
OK.. let me try it out

**Comment by SGFGOV** [comment]
is this already in the release ?

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
