### ISSUE TITLE
Customer/User session get expired too quick

### ISSUE THREAD

**Issue by iamanle** [medusajs/medusa#4574]
## Bug report
Currently the session of user is expired every day and requires users to relogin which is very inconvenience for our case which uses Mobile first.

We have our mobile app auth by Firebase Phone Number and so it's not ideal (even which email login) for users to reauth everyday. 

Potentially this could be solved by moving to Auth Token instead of Session, but still Medusa should allow to cutomize the session TTL: https://github.com/medusajs/medusa/pull/4064

### Describe the bug

Customer/User is required to relogin. 

### System information

Medusa version (including plugins): 1.10.1
Node.js version: 16.20
Database: Postgres
Operating system: Mac, Ubuntu
Browser (if relevant):

### Steps to reproduce the behavior

1. Login on Storefront
2. Next day got kicked out

### Expected behavior

Allow users to keep session on X time. Ideally 30 days or revoke if any auth change.

**Comment by pevey** [comment]
In your project config (medusa-config.js), you can actually pass through specific options to be used by express-session.  Here are the options I use, which make the session last 365 days, and refresh each time they access the site.  I believe the maxage of a cookie allowed by browsers is 400 days, so keep that in mind.  I don't store payment method tokens at the moment, so the risk of long-lasting sessions is extremely low.  If you do store payment methods, you may want to have a user enter their password to refresh the session before checkout.  But most people know now to log out of their account if they are using some random computer.
```
  projectConfig: {
    // ... other stuff
    session_options: {
      secret: process.env.COOKIE_SECRET,
      name: "connect.sid",
      resave: true,
      rolling: true,
      saveUninitialized: true,
      ttl: 365 * 24 * 60 * 60 * 1000
    }      
  },
```

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
