### ISSUE TITLE
Incomplete Cart Transaction Rollback on Error in Cart Completion Strategy

### ISSUE THREAD

**Issue by specture48** [medusajs/medusa#4698]
## Bug report
There is a bug related to the cart completion strategy transaction. When an error occurs during the process, the cart payment is still being saved, and the transaction is not rolled back as expected.
which cause Duplicate_Error (violate unique constraint)

### System information

Medusa version (including plugins):v1.13
Node.js version:v18
Database:pg
Operating system:win11

### Steps to reproduce the behavior

1-create a cart with empty items for example
2-create payment session
3- try to complete the cart
it will error out that the cart is empty 

4-add item to cart
5-complete the cart

it will error out: becase this part of authorizing and creating payment record for the cart is not rolledback
Error: Payment with cart_id cart_01H72JAA187PQH7RMS3TN33G4X already exists.

### Expected behavior
to complete the cart successfully in second completion try

**Comment by adrien2p** [comment]
When I look at the strategy, the payment creation step succeeded, then the create order from cart failed because the cart was empty. So at this point, the rollback shouldn't have rollback the payment, this is intended. Then you added the new items and re run the completion, here it should restart from the `payment_authorized` step which will try to create the order from the item, this step does not try to create the payment but to update it. 

could you share the idempotency key value in your db for this cart completion. I would like to see the step it stopped to.
