### ISSUE TITLE
Docs(Code Issue): Code Issue in /development/cache/create

### ISSUE THREAD

**Issue by alekseykim-dev** [medusajs/medusa#4723]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Good day! I'm building a platform using Medusa, and I found it bit confusing to work with "Create a Cache Module" part of the documentation that the Medusa's community provides. I thought my remark would help and decided to reach out. 

<img width="839" alt="Screenshot 2023-08-09 at 10 45 44 AM" src="https://github.com/medusajs/medusa/assets/112188056/cba9f588-9880-4e1e-94e7-e6fc076482ee">

1. The instructions for creating the index.ts file is a bit unclear. the path of the index.ts is "scr/services/index.ts", but since the documentation says to just create index.ts, it is a bit unclear where to do so. 
2. in line 3, it says "import { MemcachedCacheService } from "./services". But it should be "import MemcachedCacheService  from "./memcached-cache" because in Step1, it is written "export default MemcachedCacheService"

I hope my recommendations will help others with their projects. !hank you!

### How can this issue be resolved?

1. Review the documentation ( there is another path uncertainty in Step1
2. Give the right path or the files and correcting the code in Step 1
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by dev-bgh** [comment]
me too same issue

**Comment by shahednasser** [comment]
Thank you for submitting this issue! Will look into making it clearer and adjust the documentation accordingly.

Just to clarify, the file in Step 1 is placed in the correct directory. The `index.ts` file in step 3 should be in `src/index.ts`. That's why the import in it is correct (`./services`), however, a file is missing from the documentation which is `src/services/index.ts` that exports the service. I'll look into fixing this guide. You can alternatively change the import to `./services/memcached-cache`.

If it makes things easier, I suggest taking a look at our own [Redis Cache module](https://github.com/medusajs/medusa/tree/develop/packages/cache-redis) to understand how the structure should be like.

**Comment by alekseykim-dev** [comment]
Thank you!
