### ISSUE TITLE
`shipping_address.country_code` cleared after cart region update

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#4726]
Using Medusa `1.13.1`, 

1. Create cart
2. Set `shipping_address` and set a shipping method (`shipping_methods`).
3. Call update cart and have `region_id` in the body, with the same region id as the cart already has.

The `shipping_address` remains, but it's `country_code` is now null.
The `shipping_methods` are empty as well.

I expect it to remain as-is?

I have this use case because we want to enforce (trough middleware) the cart's region based on a field on the user profile that we control (b2b use case). So I always send the `region_id` along on every cart update call by using middleware.

**Comment by srindom** [comment]
Generally, it makes sense to clear the country code since we know that the country cannot belong to two regions so in the usual cases where you actually change the value the right thing to do is to clear the country code. That said updating to the same value is an edge case that has not been taken into account. We can look into ignoring the update under this condition.

Would it make sense for you to do a similar thing in your middleware: i.e., check if the `region_id` is different from the one on the Customer profile and only in that scenario pass the `region_id` through?

**Comment by BorisKamp** [comment]
> Generally, it makes sense to clear the country code since we know that the country cannot belong to two regions so in the usual cases where you actually change the value the right thing to do is to clear the country code. That said updating to the same value is an edge case that has not been taken into account. We can look into ignoring the update under this condition.
> 
> Would it make sense for you to do a similar thing in your middleware: i.e., check if the `region_id` is different from the one on the Customer profile and only in that scenario pass the `region_id` through?

Yeah it's a nice edge case indeed! I can do that for sure, thanks.
Up to you what you want to do with the issue, close it or solve this edge case.
