### ISSUE TITLE
Docs(Code Issue): Code Issue in /cli/reference

### ISSUE THREAD

**Issue by goughjo02** [medusajs/medusa#4814]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The described behavior of the code snippet is not the actual behavior. In the docs it says that it creates an admin user, but it actually creates a memeber. 

there is a closely related ticket here https://github.com/medusajs/medusa/issues/2617

### How can this issue be resolved?

1. perhaps specifying the role on this line would resolve the issue https://github.com/medusajs/medusa/blob/f5d8696123b371a828aa66fe6da04a5b698646f3/packages/medusa/src/commands/user.js#L37C14-L37C14
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you @goughjo02 for submitting this issue, but I'm not sure I understand. Do you mean that the issue is that it creates an admin user with the role `member`?

If so, then please know that user roles in Medusa don't actually change the user's privileges. The user, regardless of their role, are still admin users.

**Comment by shahednasser** [comment]
Closing this issue for lack of response.
