### ISSUE TITLE
Login failing on Safari but not Chromium

### ISSUE THREAD

**Issue by samhenderson511** [medusajs/medusa#4931]
# Bug report #
## Describe the bug ##
When attempting to log into the Medusa backend using Safari, I am receiving 401 errors, indicating unauthorized access. However, I am able to successfully log in using Arc (Chromium) without any issues.

The loader appears as it does in a successful login but then I get redirected to the login page instead of the dashboard.

## System information ##
Medusa version:
``` json
    "@medusajs/admin": "^7.0.1",
    "@medusajs/cache-inmemory": "^1.8.8",
    "@medusajs/cache-redis": "^1.8.8",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.9",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/medusa": "^1.15.0",
    "medusa-file-github": "^0.0.7",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.3",
    "medusa-plugin-sendgrid": "^1.3.11",
    "@medusajs/medusa-cli": "^1.3.20",
```
Node.js version: 18
Database: Postgres
Operating system: MacOS 10.15.7
Browser (if relevant): Safari (not working) & Arc (working)

## Steps to reproduce the behaviour ##
1. Go to 'https://[admin-url].vercel.app/' on Safari.
2. Attempt to log into the Medusa backend.
3. Encounter 401 error messages in logs indicating unauthorized access.

## Expected behaviour ##
I expect to be able to log into the Medusa backend successfully on Safari just as I can on Arc.

## Console logs ##
``` console
81.131.106.2 - - [01/Sep/2023:08:13:45 +0000] "GET /admin/batch-jobs?limit=100 HTTP/1.1" 401 - "https://[admin-url].vercel.app/"; "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
```

**Comment by kasperkristensen** [comment]
@samhenderson511 This is because Safari has more strict rules for cross-domain cookies. If you want it to work on Safari you need to host your server, store and admin on the same domain eg. mystore.com, api.mystore.com, admin.mystore.com. Alternatively, you can allow cross-domain tracking in your Safari settings, but that is not an actual solution. 

Also, you will want to look into not using `.vercel` domains as they are on the [Public Suffix](https://publicsuffix.org/list/) list which will also cause issues with cookies. 

Closing this as it is not directly related to Medusa :)
