### ISSUE TITLE
Medusa UI Select Component Select props outdated?

### ISSUE THREAD

**Issue by stanley-tarce** [medusajs/medusa#4938]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hello,
Currently, I am exploring the Select Component for the custom page in the Admin UI. However, some properties listed in this [documentation](https://docs.medusajs.com/ui/components/select) states that it is an invalid property. Is there a recent change that caused this? Thank you.
<img width="945" alt="Screenshot 2023-09-02 at 10 19 59 PM" src="https://github.com/medusajs/medusa/assets/79818058/3119c62d-242c-4b0b-9942-710411165fe2">

### How can this issue be resolved?

1. Import Select component
2. Apply Select Demo Code in Select Code
3. Check and compare in the documentation
...

**Comment by kasperkristensen** [comment]
Hi @stanley-tarce, 

Looks like you could be using a pre-release version of `@medusajs/ui`, as the Select component was changed just before release. Alternatively, it could be because you have a beta version of `@medusajs/admin` installed.

Make sure you have `@medusajs/admin@7.0.1` and `@medusajs/ui@1.0.0` installed, and try to clear your node_modules and re-install dependencies. 

Closing this as the component is documented correctly, if you are still facing issues after trying the above then please re-open your issue in the appropriate repository - https://github.com/medusajs/ui/issues
