### ISSUE TITLE
API Ref(admin): Issue in Delete an Invite

### ISSUE THREAD

**Issue by uzair110** [medusajs/medusa#4955]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

We do not get any ID. When creating the invite, no ID is returned.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
