### ISSUE TITLE
cacheService doesn't provide initialization message as mentioned in the Doc

### ISSUE THREAD

**Issue by blegaut** [medusajs/medusa#5047]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I follow the guideline to install redis event bus and redis cache service.
https://docs.medusajs.com/development/cache/modules/redis
I can see the following message in the logs:
`info:    Connection to Redis in module 'event-bus-redis' established`

But I can't see any message regarding the cache service. (which should be the case according to the doc): Any idea why ?
Thank you

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by Douglas-Pontes** [comment]
I have the same problem

**Comment by tanmay-d-shah** [comment]
@blegaut You have to provide some ttl value in the options. By default it takes zero and cache is not used. Hence you don't see the log.
This should be mentioned in the doc.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
