### ISSUE TITLE
Stripe hooks 404 after update to v1.16

### ISSUE THREAD

**Issue by raukaute** [medusajs/medusa#5159]
## Bug report

We just updated to v.1.16 (coming from v.1.11). Stripe hooks are now all returned a 404.

### Describe the bug

Payment and everything works fine. Just all hooks delivered by stripe are not handled. All 404.

### System information

Medusa version (including plugins): 1.16 / Admin: 7.1.0 , Stripe: 6.0.4
Node.js version: 1.18
Database: Postgres

### Expected behavior

The plugin should handle the incoming webhooks.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
