### ISSUE TITLE
Plugin Development and UI being terrible slow with HMR

### ISSUE THREAD

**Issue by xmdcode** [medusajs/medusa#5203]
Hello all,

I am trying to contribute to an open source plugin (medusa-plugin-feeds) and i am writing all the frontend ui for now. 

While trying to develop the ui with custom components/pages , i can't really develop since after 2-3 saves on the file it bugs out , slows and i need to kill the project and start it again.

This REALLY slows the development if you need to make more complex plugins that consist more than 1 page components etc. 

Is there any possible speed update to be expected any times soon?

P.S. I need to turn off 2-3 extensions on VSCode so i can continue develop since for example Prettier does 1 minute to save.(Don't have problem on other projects based on vite/nextjs etc).

**Comment by kasperkristensen** [comment]
Hi @rounsmith,

The HMR is quite slow when working with Admin Extensions, but normally it's 1-3 seconds (which is because it does a full page reload on each save). This is something I am aware of and will invest some time into improving when I get the time. 

It would be great if you could describe your workflow, are you building your pages directly in a Medusa project, with the intention of moving it over to the plugin afterward? Or are you building them out directly in the plugin, with `watch` running, and linking the plugin into a Medusa project?

If it's the first case then this might be a result of not ignoring the `.cache` folder in eslint and prettier. The `.cache` folder contains the entire admin project, so if eslint and prettier are getting run against that on every save it could definitely be a cause of a significant increase in the time it takes for actions to finish. 

Could you try to ignore it, and if that does not improve anything then a reproducible repo would be great. Please also provide which version of `@medusajs/admin` you are using, as there were some improvements to make the development workflow less error-prone, so if you are on an older version updating might also help.

**Comment by xmdcode** [comment]
> Hi @rounsmith,
> 
> The HMR is quite slow when working with Admin Extensions, but normally it's 1-3 seconds (which is because it does a full page reload on each save). This is something I am aware of and will invest some time into improving when I get the time.
> 
> It would be great if you could describe your workflow, are you building your pages directly in a Medusa project, with the intention of moving it over to the plugin afterward? Or are you building them out directly in the plugin, with `watch` running, and linking the plugin into a Medusa project?
> 
> If it's the first case then this might be a result of not ignoring the `.cache` folder in eslint and prettier. The `.cache` folder contains the entire admin project, so if eslint and prettier are getting run against that on every save it could definitely be a cause of a significant increase in the time it takes for actions to finish.
> 
> Could you try to ignore it, and if that does not improve anything then a reproducible repo would be great. Please also provide which version of `@medusajs/admin` you are using, as there were some improvements to make the development workflow less error-prone, so if you are on an older version updating might also help.

 I am doing it first way since it's way easier for me to develop the components/pages. I will try the cache trick. I am using the 7.1.1 version of @medusajs/admin

**Comment by xmdcode** [comment]
I tried with a .prettierignore file to ignore node_modules and .cache but after 2nd save on same file , prettier vs code extension hangs indefinetely except i disable it.

Here is a reproducible repo. 

https://github.com/rounsmith/Admin-Medusa-Plugin

**Comment by alexmilde** [comment]
i seem to have a similar problem.
vanilla project setup: (yarn, intel mac)

i added a custom route `src/admin/routes/mypage.tsx`

`yarn dev`

changing anything results in a 5 - 6 seconds recompile. 

im not shure whether this is expected behaviour, or im missing something.

i tried the cache trick with no effect.
