### ISSUE TITLE
Can't find typings when using medusa-react with typescript

### ISSUE THREAD

**Issue by zzmingo** [medusajs/medusa#5209]
Type error: Could not find a declaration file for module 'medusa-react'. '/codebuild/output/src1039626502/src/aimerce-frontend/node_modules/medusa-react/dist/index.mjs' implicitly has an 'any' type.
                                    There are types at '/codebuild/output/src1039626502/src/aimerce-frontend/node_modules/medusa-react/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'medusa-react' library may need to update its package.json or typings.

**Comment by kspacja** [comment]
I have the same problem.

**Comment by lazaro9318** [comment]
In the [troubleshooting](https://docs.medusajs.com/medusa-react/overview#:~:text=by%20Medusa%20React.-,Troubleshooting,-%3A%20Could%20not%20find) section there is a solution already. 

Make sure to set moduleResolution in your `tsconfig.json` to nodenext or node: 
`{
  "compilerOptions": {
    "moduleResolution": "nodenext",
    // ...
  },
  // ...
}`

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
