### ISSUE TITLE
GET shipping-options broken after deleting region

### ISSUE THREAD

**Issue by jeroenkroese** [medusajs/medusa#5219]
### System information

Medusa version (including plugins): @medusajs/medusa": "^1.16.0",
Node.js version: 18
Database: Postgres

### Steps to reproduce the behavior

1. Create new Region 
2. Create shipping option
3. Delete region
4. GET {{baseUrl}}/store/shipping-options

### Expected behavior

Returns shipping options

### Result

``` 
{
    "type": "not_found",
    "message": "Region with reg_01HB93FWDTAARWFCHGZYWSKT6N was not found"
}
```

**Comment by ruchikamuddinagiri** [comment]
I can take a look at this!

**Comment by Anderson-Reges** [comment]
Cleaning the storage should solve the problem, since you deleted the old region, but it is still saved on the storage

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
