### ISSUE TITLE
Invalid type for product variant

### ISSUE THREAD

**Issue by Alexnortung** [medusajs/medusa#5241]
### Describe the bug

When finding a `ProductVariant` for example through its repository, some fields are not set as nullable even though they can be null. 

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Create a service file
2. get the `ProductVariant` repository (`variantRepository = this.activeManager_.getRepository(ProductVariant);`)
3. find a product variant `variantRepository.findOne(...)`
4. hover over `variant.barcode` and observe that the type is a string.
5. console.log `variant.barcode` and observe that the value is null.

### Expected behavior

I expect barcode and multiple other fields to have correct typings, both to avoid runtime errors but also being able to assign null if needed.

**Comment by adrien2p** [comment]
The references pr should fix that

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
