### ISSUE TITLE
Returns not listed in receive return modal

### ISSUE THREAD

**Issue by j00p34** [medusajs/medusa#5263]
### Describe the bug

Returns not showing up in Receive return 

### System information

Medusa version (including plugins): @medusajs/admin@7.1.2
Node.js version: 20.6.1
Database: supabase
Operating system: Linux
Browser (if relevant):

### Expected behavior

returns listed

### Screenshots

![Screenshot from 2023-09-29 14-27-40](https://github.com/medusajs/medusa/assets/8323598/1a322e47-275f-4db3-844b-e290ed0f2f86)
![Screenshot from 2023-09-29 14-28-10](https://github.com/medusajs/medusa/assets/8323598/8f05c47b-7ca2-4dd8-a7ec-b5a85b5a49ad)

**Comment by Xxsource98** [comment]
I got the same issue

**Comment by the-special-character** [comment]
+1

**Comment by olivermrbl** [comment]
It might be because your items are yet to be shipped. Any reason why you are not canceling the fulfillment instead of requesting a return?

**Comment by Xxsource98** [comment]
> It might be because your items are yet to be shipped. Any reason why you are not canceling the fulfillment instead of requesting a return?

Exactly, I figured it out and forgot to mark it here. You have to ship items first.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
