### ISSUE TITLE
Medusa Admin UI crash when having a custom batch job

### ISSUE THREAD

**Issue by pepijn-vanvlaanderen** [medusajs/medusa#5289]
### Describe the bug

When using a custom batch job, the batch job activity card component crashes the Medusa Admin UI.

### Steps to reproduce the behavior

1. Create a custom batch job strategy
2. Run the batch job through API
3. Open the activity sidebar in Medusa Admin UI
4. The UI crashes

### Expected behavior

The UI to render the custom job activity card properly.

### Error message

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at e_ (/app/30.474287bc.chunk.js:1:108664)
    at oO (/app/main.709c6af3.js:18:60913)
    at u (/app/main.709c6af3.js:18:119434)
    at sI (/app/main.709c6af3.js:18:99087)
    at /app/main.709c6af3.js:18:98954
    at sN (/app/main.709c6af3.js:18:98961)
    at sE (/app/main.709c6af3.js:18:95713)
    at sk (/app/main.709c6af3.js:18:96102)
    at n4 (/app/main.709c6af3.js:18:44823)
    at /app/main.709c6af3.js:18:93613

### Solution

Fixed by https://github.com/medusajs/medusa/pull/5288

**Comment by mortenengel** [comment]
I just came to report this exact bug as well - I believe it's a new issue as we have been working with a custom batch job for a while without seeing this issue. (But I don't see the exact code being pasted below having been changed recently)

The issue lies in this hardcoded list: 
```
  const operation = {
    "product-import": BatchJobOperation.Import,
    "price-list-import": BatchJobOperation.Import,
    "product-export": BatchJobOperation.Export,
    "order-export": BatchJobOperation.Export,
  }[batchJob.type]
```

the operation will be undefined for custom batch jobs, and is used like this before there is a result.file_key:
```
    const fileSize = batchJob.result?.file_key
      ? bytesConverter(batchJob.result?.file_size ?? 0)
      : {
          confirmed: `Preparing ${operation.toLowerCase()}...`,
          preprocessing: `Preparing ${operation.toLowerCase()}...`,
          processing: `Processing ${operation.toLowerCase()}...`,
          completed: `Successful ${operation.toLowerCase()}`,
          failed: `Job failed`,
          canceled: `Canceled batch ${operation.toLowerCase()} job`,
        }[batchJob.status]
```

would it be just adding ?? batchJob.type  after the first code block, to fall back to the underlying operation name for custom jobs?

**Comment by mortenengel** [comment]
Ahh - didn't notice there was already a pull request - perfect :)
