### ISSUE TITLE
Admin UI activity drawer z-index issue

### ISSUE THREAD

**Issue by pepijn-vanvlaanderen** [medusajs/medusa#5363]
### Describe the bug

The activity drawer has a wrong z-index after latest UI release.
![Scherm­afbeelding 2023-10-12 om 13 29 20](https://github.com/medusajs/medusa/assets/7559384/5bd73cb4-c15c-4468-8244-d8bb07c40208)

Also the activity drawer does not use the Radix dialog primitive like other modals in the Admin UI.

I have created a PR to address this issue: https://github.com/medusajs/medusa/pull/5362

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
