### ISSUE TITLE
Spill over in the admin

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#5378]
Hi,

The admin page's responsive behaviour needs improvement, titles and text tend to spill over

![image](https://github.com/medusajs/medusa/assets/97059996/9503b7a4-c067-4534-9cbe-3687da53dcc1)

**Comment by SGFGOV** [comment]
You notice, the word published, thumbnails etc spill over outside the region. This affects responsive behavior

**Comment by vineetjk** [comment]
You are correct, Overflow needs to be handled. 
I would like to work on this issue if its ready to take.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
