### ISSUE TITLE
Can't rewrite default route validators without class-validator

### ISSUE THREAD

**Issue by d1sna** [medusajs/medusa#5446]
Hi, guys
while im trying to rewrite validator for route "api/routes/admin/price-lists/update-price-list", i can do this only with class-validator 
it's working: 
<img width="816" alt="Снимок экрана 2023-10-23 в 10 24 04" src="https://github.com/medusajs/medusa/assets/56303300/d8d42fa9-abf4-4e9e-90de-617f8bdccbe4">

but if i delete it's not working totaly : 

<img width="816" alt="Снимок экрана 2023-10-23 в 10 33 20" src="https://github.com/medusajs/medusa/assets/56303300/477f4259-27f2-4299-bbdc-d59aca4a83e7">

<img width="1021" alt="Снимок экрана 2023-10-23 в 10 36 27" src="https://github.com/medusajs/medusa/assets/56303300/0c0ad04e-00c4-4410-aea3-799ab6058030">

it's not big problem for me, i can use "@IsOptional()" decorator, but i've spent a lot of time to understand it, just add it in documentation or fix this behaviour. Thanks :)

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
