### ISSUE TITLE
Tamil Translation Keys are in different order as compared to English.

### ISSUE THREAD

**Issue by its-kunal** [medusajs/medusa#5491]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

- Recently the Tamil translation was added in the repo. But the issue is keys are in a different order as compared to English translation keys.
- Some of the keys are not translated. The Tamil translation only contains - 1922, but in the English translation, there are 2011 keys.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by its-kunal** [comment]
@VariableVic, please review my pull request. PR- #5494

**Comment by its-kunal** [comment]
@olivermrbl, Please review my pull request. PR - #5494

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
