### ISSUE TITLE
Some of the translation keys are missing.

### ISSUE THREAD

**Issue by its-kunal** [medusajs/medusa#5492]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

As compared to English translation, some of the locales are not updated.
Following are the translations:
1. Arabic (ar)
2. Spanish (es)
3. Polish (pl)

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by amisdun** [comment]
@its-kunal can you explain further? I want to pick up this issue

**Comment by its-kunal** [comment]
In the `packages/admin-ui/ui/public/locales` directory there are translations available in different languages. But some translation keys are missing in the language mentioned above as compared to English translation. Also, the json file is not in proper order.

**Comment by undercontr** [comment]
I also experienced this issue while translating to Turkish, it seems that some keys are missing and not shown right on the screen, they still show English ones even though those keys are translated

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
