### ISSUE TITLE
Docs(Code Issue): unrelatable run command in /admin/widgets

### ISSUE THREAD

**Issue by OmarMHawash** [medusajs/medusa#5695]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

the following command was provided in the **/admin/widgets** doc:
`npx @medusajs/medusa-cli@latest develop`.

Which could be replaced by: `yarn build`, then `medusa develop`. just like in other docs.

Also forces to download the **@medusajs/medusa-cli** package as a dependency, instead of a dev dependency.

### How can this issue be resolved?

1. replace command `npx @medusajs/medusa-cli@latest develop` with: `yarn build`, then `medusa develop`

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue @OmarMHawash . We prefer using `npx` across the documentation so that if scripts in the starter default used to create a Medusa backend (such as the `build` script) changes, we make sure documentation pages aren't affected.

However, it makes sense to simplify the `npx @medusajs/medusa-cli@latest develop` to `npx medusa develop` as we usually do with other documentation pages. If you're interested please open a PR with that change.

**Comment by OmarMHawash** [comment]
yes, I see the use of **npx**
I was also concerned about installing it as a dependency instead of devDependency
