### ISSUE TITLE
Remove deprecated Medusa-plugin-filestorage-local plugin page (Or display that it's now @medusajs/file-local)

### ISSUE THREAD

**Issue by anchemy** [medusajs/medusa#5782]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

[This plugin](https://medusajs.com/plugins/medusa-plugin-filestorage-local/) is a deprecated npm package that is still up on the Medusa website plugins section. 

### How can this issue be resolved?

Good day!

I would like to suggest to have [this page](https://medusajs.com/plugins/medusa-plugin-filestorage-local/) either:

(a) replaced as a redirection landing page to [@medusajs/file-local](https://www.npmjs.com/package/@medusajs/file-local), since @medusajs/file-local is the replacement after all. This page could also indicate important details such as the following:
- @medusajs/file-local is already pre-installed when you create a Medusa project.
- @medusajs/file-local is not suitable for production environments.
- medusa-plugin-filestorage-local is indeed deprecated
- medusa-plugin-filestorage-local is no longer maintained

(b) completely deleted since it is deprecated.

Having it still up might cause more confusion. Thank you!

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for submitting this issue. This plugin is not created by the Medusa team. It's created by a community member. You can distinguish community and official plugins through the Medusa logo on the plugin's icon (see [here](https://medusajs.com/plugins/@medusajsfile-local/) as an example)

However, I can see that the page of the `@medusajs/file-local` plugin doesn't have the correct "storage" category, and its because the [package.json file](https://github.com/medusajs/medusa/blob/develop/packages/medusa-file-local/package.json) doesn't have the keyword `medusa-plugin-storage`. Would you like to open a PR that adds the keyword?

**Comment by anchemy** [comment]
> Thanks for submitting this issue. This plugin is not created by the Medusa team. It's created by a community member. You can distinguish community and official plugins through the Medusa logo on the plugin's icon (see [here](https://medusajs.com/plugins/@medusajsfile-local/) as an example)
> 
> However, I can see that the page of the `@medusajs/file-local` plugin doesn't have the correct "storage" category, and its because the [package.json file](https://github.com/medusajs/medusa/blob/develop/packages/medusa-file-local/package.json) doesn't have the keyword `medusa-plugin-storage`. Would you like to open a PR that adds the keyword?

Hi! Sure, I'll open a PR. Thanks so much for your help! :)
