### ISSUE TITLE
Don't receive any email with instructions how to reset Admin password

### ISSUE THREAD

**Issue by vasilemidrigan** [medusajs/medusa#5883]
### Issue Summary

Don't receive any email when clicking "Send reset instructions" in order to get the instructions how to reset my password for Login Admin. From docs, there is a recommendation to get in touch with technical team to ensure that the email service is setup correctly. So I guess that maybe the problem. 

### Additional details

After I click send reset instructions, I get a message on the screen that the message was successfully sent, however I don't get any email.

**Comment by vasilemidrigan** [comment]
Is there another way to change the password of the Admin Dashboard?

**Comment by shahednasser** [comment]
Hello, you'll need to setup a Notification service to get an email, such as [SendGrid](https://docs.medusajs.com/plugins/notifications/sendgrid).

As a workaround, you might need to access the database to get the reset password token, then open the admin to the route `/reset-password?token=<your-reset-token>`

**Comment by vasilemidrigan** [comment]
Great! Thanks for help!

**Comment by AbhinavChavareTechcopain** [comment]
please elaborate. 
I have installed the send grid plugin with the API and user_reset_password
but we don't get the mail,
getting 204 No Content while trying to reset the password to the user admin.
![image](https://github.com/medusajs/medusa/assets/126047812/256300d2-b3b8-418d-af45-f31aa7bf14a5)
please guide me for the same.

**Comment by shikharcodess** [comment]
Hey @AbhinavChavareTechcopain have you found the solution? I'm facing exact same issue as you are facing. Sendgrid is already settup and getting API to return 204 No content status but never received the email.

**Comment by suryakun** [comment]
Using medusa-react producing the same error. get /admin/users/password-token  {"type":"invalid_data","message":"property email should not exist"}

**Comment by claudiutudor** [comment]
Hi @ShikharY10  and @AbhinavChavareTechcopain,

Your request and the 204 No Content response are expected behavior. The next step is to implement a subscriber that handles the `user.password_reset` event.

When you click "Send reset instructions" after typing the email of the admin whose password you want to reset, check your backend logs. You’ll likely see an error similar to this:

**`An error occurred while processing user.password_reset: Error: Sendgrid service: No template was set for event: user.password_reset.`**

To resolve this, follow these steps:

1. Create a New Subscriber:

In your src/subscribers folder, create a new file named admin-reset-password.ts. Add the following implementation:

```javascript
import { type SubscriberConfig, type SubscriberArgs } from "@medusajs/medusa";

export default async function handleAdminPasswordReset({
  data,
  eventName,
  container,
  pluginOptions,
}: SubscriberArgs<Record<string, string>>) {
  const sendGridService = container.resolve("sendgridService");

  const resetPasswordLink =
    process.env.BACKOFFICE_URL + "/reset-password?token=" + data.token;

  const templateId = process.env.SENDGRID_RESET_ADMIN_PASSWORD_TEMPLATE_EN;

  sendGridService
    .sendEmail({
      templateId: templateId,
      from: process.env.SENDGRID_FROM,
      to: data.email,
      dynamic_template_data: {
        reset_password_link: resetPasswordLink,
      },
    })
    .catch((err) => {
      // Handle SendGrid error (optional: add logging here)
    });
}

export const config: SubscriberConfig = {
  event: "user.password_reset",
  context: {
    subscriberId: "reset-admin-password-handler",
  },
};
```


2. Set Up the Required Environment Variables:

    Ensure you have the following variables configured in your `.env` file:
    
   - `BACKOFFICE_URL` (e.g., the URL to your admin dashboard)
   - `SENDGRID_RESET_ADMIN_PASSWORD_TEMPLATE_EN` (your SendGrid template ID)
   - `SENDGRID_FROM` (the sender's email address)
