### ISSUE TITLE
Medusa backend api didn't work on backend with incognito mode and mobile broswer

### ISSUE THREAD

**Issue by luckyrsa56** [medusajs/medusa#5916]
Hello
I have some issues with medusa backend api part 
It works with chrome broswer on the desktop but It didn't work with incognito mode and mobile broswer 
I am using Next.js for frontend and for backend, I am using medusa.js 
![image](https://github.com/medusajs/medusa/assets/152653815/ad8c3eca-256e-4066-a241-26d6d7d86643)
Medusa.js version :
![image](https://github.com/medusajs/medusa/assets/152653815/75b78891-3bbe-45a9-8357-085e30b34bd2)
![image](https://github.com/medusajs/medusa/assets/152653815/b999d268-7ae4-4f5b-b1a7-a84f03f66886)

**Comment by adrien2p** [comment]
Isn't it a cookie issue since you are in incognito?

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
