### ISSUE TITLE
Admin API Routes with same path but different param names are conflicting

### ISSUE THREAD

**Issue by AlexTechNoir** [medusajs/medusa#5927]
Hello! 

Not sure if it's a bug or expected behaviour

I created 2 Admin API Routes: `api/admin/storage-images/[imgId]/route.tsx` and `api/admin/storage-images/[variantId]/route.tsx`

When I query the second one, like this: `http://localhost:9000/admin/storage-images/${variantId}`, the request goes to the first one (probably alphabetically first) - is this supposed to be like this? Meaning, we can't create API routes with the same path, but different param names?

**Comment by kasperkristensen** [comment]
Hi @AlexTechNoir

No you cannot do that, since the endpoints can match the same paths. This means that the endpoint that gets loaded first will be the one used. You should make your endpoints more specific, eg. `admin/storage-images/[imgId]/route.tsx` and `/admin/storage-images/variants/[variantId]/route.tsx`
