### ISSUE TITLE
The phone number is not displayed on the admin panel orders page, but the phone number is displayed on the customer page.

### ISSUE THREAD

**Issue by luckyrsa56** [medusajs/medusa#5956]
![image](https://github.com/medusajs/medusa/assets/152653815/e5f9bd4a-1373-46a2-aad8-8f42b6445d08)
![image](https://github.com/medusajs/medusa/assets/152653815/ce74699c-6481-45b0-9c5a-da9f39833475)

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
