### ISSUE TITLE
How to make some updates to the backend admin ui interface?

### ISSUE THREAD

**Issue by Sayid1** [medusajs/medusa#5998]
admin ui is installed in node_modules as an npm package. I want to make a little modification to the management interface, but I cannot directly modify the files in node_modules.

For example, what should I do to modify the css/html here?
The actual problem is much more than that simple. I just give an easy-to-understand example.

<img width="926" alt="image" src="https://github.com/medusajs/medusa/assets/29008437/2b8b2963-3e88-4df5-9b26-01352adc3fab">

I know this question should be asked in discord, but no one in discord answered me.

so I raised an issue. People here are more helpful.

**Comment by peterlama** [comment]
Hey, I'm not core a contributor of course, but I previously have had the same question, and have seen it asked a few other times too. Basically medusa doesn't support that and they don't plan too (which makes sense, because having infinite customizability is too hard to maintain reliably). The following thread and the linked discussions show what the options are: https://github.com/medusajs/medusa/discussions/5942

The supported way of adding custom UI to a page is by adding a separate widget instead of customizing the core UI: https://docs.medusajs.com/admin/widgets

If you just need to hide some things, you might be able to add a widget that renders nothing, but has a useEffect where you can hack the dom from, as mentioned in the above linked discussion.

Lastly, if you need to make extensive customizations to the core UI for whatever reason, you can fork the admin packages (which is what I ended doing). However, that is definitely discouraged and it would it be a particular bad time to do it because of the new admin that is being worked on: https://github.com/medusajs/medusa/discussions/5954

**Comment by olivermrbl** [comment]
Thanks for chiming in @peterlama :)

**Comment by JoshFialkoff** [comment]
Is it possible to remove this via css or some other front-end method?
