### ISSUE TITLE
Property 'prices' does not exist on type 'ProductVariantDTO'

### ISSUE THREAD

**Issue by Nekxio** [medusajs/medusa#6067]
### Describe the bug

When I want to use the type ProductDTO and ProductVariantDTO for my product, I get an error concerning the price parameter.
After checking the source code, I've noticed that there is no price parameter in ProductVariantDTO, resulting in the following error:
`Error: Property 'prices' does not exist on type 'ProductVariantDTO'. (ts)`

### System information

Medusa version (including plugins):
- sveltekit-medusa-client: 3.1.2
- @medusajs/types: 1.11.10

Node.js version:
- 21.5.0

### Code snippets
```
export let product: ProductDTO;
const price: number = product.variants[0].prices[0].amount / 100;
```

### Potential fix

path: packages/types/src/product/common.ts
Add prices parameter to ProductVariantDTO type

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
