### ISSUE TITLE
Segment plugin is ignoring include_tax setting

### ISSUE THREAD

**Issue by aldo-roman** [medusajs/medusa#6069]
### Describe the bug

Our store is located in a region where all taxes must be included in the price. Thus, when controlling our revenue, we prefer to have it with taxes included. The current Segment plugin is always removing the tax from the reported price.

### Steps to reproduce the behavior

1. Setup Medusa (configured to include taxes in price) and Segment
2. Place an order
3. Go to Segment debugger
4. The property `reporting_revenue` for each product is subtotal price, without tax

### Expected behavior

The property `reporting_revenue` for each product is the total price, including tax

<img width="429" alt="image" src="https://github.com/medusajs/medusa/assets/497197/372b4b0b-a7ec-4795-a8ac-39edd525fe05">

### Code snippets

https://github.com/medusajs/medusa/blob/8472460f533322cc4535199aa768ac163021bc79/packages/medusa-plugin-segment/src/services/segment.js#L118

**Comment by srindom** [comment]
@aldo-roman, thanks for opening the issue. Unfortunately, we will not change this because of the following two reasons:
1. Changing this would make the plugin useless in multi-region sales since taxes across regions can differ and you would therefore not get a meaningful understanding of your stores performance. 

2. Furthermore, it's not inline with Segments ecommerce spec: https://segment.com/docs/connections/spec/ecommerce/v2/#order-completed. 

You can always use the `reporting_total` value instead which includes taxes - does this not satisfy your use case?

**Comment by aldo-roman** [comment]
Hello @srindom Yeah this makes sense. Outside of the US we mostly need revenue with taxes rather than without.

The `reporting_total` field you mention is for the whole purchase, but the items in `products` array only have a `price` field. The Segment spec also does not specify it the price is with or without taxes. Out of the US, the individual price would be with taxes.

The behaviour was confusing as the plugin is going the extra mile to take the taxes out of the items prices, which we set all included. This is why I mention that the `include_tax` flag should be followed in the computation.

Another way would be to have both values reported, eg. `price` and `price_without_taxes`.
