### ISSUE TITLE
[ProductVariantService] : Improve reliability of option management

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#61]
There are a few shortcomings in the product variant service's management of option values. 

Firstly, right now it is possible to add an option value to a variant despite the fact that the product the variant belongs to doesn't have an option title for that value. I.e. a product can have an option with title "Size", but the `ProductVariantService` would allow us to add both a "Size" and a "Color" option. 

Likewise, the `ProductVariantService` would allow us to delete the "Size" option, even though the product has the option defined. 

We need to enforce that the product variants always have the same number of option values as the number of its top level product's options.

The reason why we have failed to do this initially is because injecting the `ProductService` as a dependency in the `ProductVariantService` would create a circular dependency. We therefore need to consider an alternative solution where the validation is done prior to making the call to `addOptionValue`, or we could inject the `ProductModel` as a dependency.

I feel that the latter is safest as that takes away the requirement from the interface layer to do validation, however, we haven't injected models not "belonging" to the service anywhere else, so we should maybe consider what implications this implementation could have.

**Comment by olivermrbl** [comment]
I think, that we should consider refactoring the ProductVariantService, as mentioned in #66. All product variant operations should go through the ProductService. This only makes sense, due to the nature of the product to product variant relationship. They are so closely connected, that I would see no problem in such refactoring. 

As we discussed last week, we still keep all the product variant specific operations in the ProductVariantService. But as soon as the ProductService gets involved, we should refactor it. This is not only a reasonable solution, but also fairly quick to do. 

Let me know what you think?
