### ISSUE TITLE
admin-ui: ActivityCard unable to control the display and hiding of dots

### ISSUE THREAD

**Issue by wangjue666** [medusajs/medusa#6172]
now, It is also impossible to delete a batch job.

![image](https://github.com/medusajs/medusa/assets/24707417/6d0d7100-5f09-49a5-af21-74c33a0a7de3)

https://github.com/medusajs/medusa/blob/9a3326a56e1b1a779eee9c38474483a51da6a6d9/packages/admin-ui/ui/src/components/organisms/batch-jobs-activity-list/index.tsx#L242

here status is always `true`, May I ask if medusa is considering adding deletion and read functions here?

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
