### ISSUE TITLE
Segment plugin using depercated sdk

### ISSUE THREAD

**Issue by Edan-Swipik** [medusajs/medusa#6187]
### Describe the bug

medusa segment plugin is using a deprcated segment plugin:
(https://github.com/segmentio/analytics-node)

further more the subscibers for this plugin raising errors on startup:
```
warn:    The subscriber in /home/server/node_modules/medusa-plugin-segment/subscribers/order.js is missing a config.
warn:    The subscriber in /home/server/node_modules/medusa-plugin-segment/subscribers/swap.js is missing a config.
```

### Expected behavior

plugin should use the supported [npm package](https://www.npmjs.com/package/@segment/analytics-node)

subscribers should have a config to prevent warnings on startup EDIT: - subscribers issue has been resolved with: https://github.com/medusajs/medusa/pull/5904

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
