### ISSUE TITLE
Typos for English locale in admin-ui

### ISSUE THREAD

**Issue by reza-sadeghzadeh** [medusajs/medusa#6368]
Some typos for keys are like:

```typescript
// line 1607 
"new-change-availablity": "Change availability",
//              ^ 
```

```typescript
// line 1395
"price-list-details-notification-succes-title": "Price list updated",
//                                  ^ 
```

No fix for them sorry, I don't know the usage place of the locale throughout the project.
But I created a PR on fixing some typos for the values inside this json file here #6367

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
