### ISSUE TITLE
Totals not correct

### ISSUE THREAD

**Issue by rightalign-io** [medusajs/medusa#6460]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I am trying to use medusa for my e-comerce store and i realized that each time i add items to the cart the price is multiplied by 10, i am not sure why and if its above 10 its multiplied by 100. This might be issue with the currency Rand for south africa but a friend of mine in austria claims to have a similar issue

### How can this issue be resolved?

1.make the total service accessible so we can see how its calculated and adjust it correctly
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by sradevski** [comment]
@rightalign-io can you please send a recording or something else to support this issue? Thanks!

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
