### ISSUE TITLE
Unable to create module

### ISSUE THREAD

**Issue by WojciechxFalkowski** [medusajs/medusa#6495]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hi,

I've spent some time trying to figure this out, but I haven't had much luck. I followed all the steps in the documentation about creating a module ([MedusaJS documentation](https://docs.medusajs.com/development/modules/create#optional-step-0-project-preparation)), but I couldn't finish it. I encountered an issue
 ![image](https://github.com/medusajs/medusa/assets/49166265/a7a432b2-270c-4163-b35f-c6c96c49a5e3)

Project structure
![image](https://github.com/medusajs/medusa/assets/49166265/520dee5c-0f04-4f11-b06d-8235c5f5e6b1)

Project structure:

"medusa-backend-for-nuxt": primary Medusa backend
cache: module

It looks like the resolve property in medusa.config.js is incorrect, but I did everything as it was described in the documentation.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

For any questions and tips, please join our Discord channel!
