### ISSUE TITLE
Error: Unknown authentication strategy "firebase.admin.medusa-auth-plugin_firebase"

### ISSUE THREAD

**Issue by ishaqkhattana** [medusajs/medusa#6528]
### Describe the bug

I am trying to implement firebase auth in Medusa, for which I've setup a Firebase project and it works when using the Firebase SDK from another application. To implement firebase auth in a Medusa project, I've followed the following guide to the word: 
https://medusa-plugins.vercel.app/authentication/firebase
(I've also installed the plugin `yarn add medusa-plugin-auth`)

### System information

Medusa version (including plugins): Medusa v1.20.2, medusa-plugin-auth v1.10.3
Node.js version: v20.10.0
Database: PostgreSQL
Operating system: MacOS
Browser (if relevant): 

### Steps to reproduce the behavior
1. Follow the guide: https://medusa-plugins.vercel.app/authentication/firebase
2. Send a GET request to /admin/auth/firebase from Postman

### Expected behavior

The request should return a 200 response with a session cookie set

### Code snippets

<details><summary>medusa-config.js</summary>

```
{
    resolve: "medusa-plugin-auth",
    /** @type {import('medusa-plugin-auth').AuthOptions} */
    options: [
      {
        type: "firebase",
        // strict: "all", // or "none" or "store" or "admin"
        strict: "none",
        identifier: "firebase",
        credentialJsonPath: CredentialJsonPath,
        admin: {
          authPath: '/admin/auth/firebase',
          // expiresIn: 24 * 60 * 60 * 1000,
          verifyCallback: (container, decodedToken, strict) => {
          }
        },
        store: {
          // authPath: '/store/auth/firebase',
          // expiresIn: 24 * 60 * 60 * 1000,
          // verifyCallback: (container, decodedToken, strict) => {
          //    // implement your custom verify callback here if you need it
          // }
        }
      }
    ]
  },

```

</details>

### Additional context

Add any other context about the problem here

**Comment by xyzones** [comment]
This is a config issue i believe, please check if you have set correctly Firebase Service Account Key file

**Comment by ishaqkhattana** [comment]
@xyzones Thank you for the prompt response, it was indeed a config issue. I've run into another issue, however, and would appreciate some more help.
While following the code snippet in the plugin guide:

```
const firebaseLogin = async (token: string) => {
    await fetch(`${medusa_url}/${authPath}`, {
        method: 'GET',
        headers: {
            Authorization: `Bearer ${token}`
        },
        credentials: 'include'
    })
}
```

I'm getting a 401 unauthorized response. What is token here? I've tried the medusa JWT token retrieved from `/auth/admin/token` to no avail.

**Comment by xyzones** [comment]
@ishaqkhattana check the admin api docs please

**Comment by kelvinnmugendi** [comment]
@ishaqkhattana did you find a solution to this (401 unauthorized response)

**Comment by balramxyadav** [comment]
Facing the same problem here, Did someone get a fix?

**Comment by KareemAbbas1** [comment]
I'm also trying to add medusa-auth-plugin, but I'm facing two problems. The first one is how to add the following function to my login flow as Medusa doesn't provide any way to edit or override the login flow in the admin dashboard. From what I understood, this function needs to be called after a successful login in order to store the token returned from the login in the headers. So how to call this function after a successful login.
`const firebaseLogin = async (token: string) => {
    await fetch(`${medusa_url}/${authPath}`, {
        method: 'GET',
        headers: {
            Authorization: `Bearer ${token}`
        },
        credentials: 'include'
    })
}`

The second problem is when I deploy the project:
The server is unable to reach the link to CredentialJsonPath. I put the json credential in a local file in my project in a folder called config in the src, during development in my local environment it's working fine the the path to CredentialJsonPath is in reach, but when I deploy to Railway the path is out of reach or the server cannot resolve the path(CredentialJsonPath).

**Comment by KareemAbbas1** [comment]
> @xyzones Thank you for the prompt response, it was indeed a config issue. I've run into another issue, however, and would appreciate some more help. While following the code snippet in the plugin guide:
> 
> ```
> const firebaseLogin = async (token: string) => {
>     await fetch(`${medusa_url}/${authPath}`, {
>         method: 'GET',
>         headers: {
>             Authorization: `Bearer ${token}`
>         },
>         credentials: 'include'
>     })
> }
> ```
> 
> I'm getting a 401 unauthorized response. What is token here? I've tried the medusa JWT token retrieved from `/auth/admin/token` to no avail.

I'm also trying to configure that plugin, and I'm facing two problems. The first one is the one mentioned here. The second problem is when I deploy the project:
The server is unable to reach the link to CredentialJsonPath. I put the json credential in a local file in my project in a folder called config in the src, during development in my local environment it's working fine the the path to CredentialJsonPath is in reach, but when I deploy to Railway the path is out of reach or the server cannot resolve the path(CredentialJsonPath).

**Comment by KareemAbbas1** [comment]
> @xyzones Thank you for the prompt response, it was indeed a config issue. I've run into another issue, however, and would appreciate some more help. While following the code snippet in the plugin guide:
> 
> ```
> const firebaseLogin = async (token: string) => {
>     await fetch(`${medusa_url}/${authPath}`, {
>         method: 'GET',
>         headers: {
>             Authorization: `Bearer ${token}`
>         },
>         credentials: 'include'
>     })
> }
> ```
> 
> I'm getting a 401 unauthorized response. What is token here? I've tried the medusa JWT token retrieved from `/auth/admin/token` to no avail.

@kevinrobert3 @balramxyadav @ishaqkhattana 
The referred token to here is the accessToken returned by Firebase after successfully authenticating the user. In my case, the 401 error was caused by a ```CORS``` issue. The endpoint mentioned returns a session cookie that can be used to authenticate with the store API, as outlined in the plugin documentation.

In the plugin configuration, there's a ```strict``` attribute, which sets the ```SameSite``` attribute on the cookie. If you don't specify a value for SameSite (leaving it commented out as shown in the docs), the browser defaults it to ```Lax```. This means cookies are only sent for top-level navigation requests, not for cross-origin requests. You can learn more about the SameSite attribute [here](https://medium.com/@salimian/cookie-defense-why-the-samesite-of-cookies-matters-as-security-05ea6d7afe07#:~:text=Lax%3A%20(default),social%20media%20platforms.).

In my particular case, I was implementing phone number authentication and was using ```127.0.0.1``` as the store URL because Firebase blocks ```localhost``` for mobile number authentication. Despite including ```127.0.0.1:8000``` in the ```STORE_CORS``` configuration for Medusa.js, I still encountered issues. Eventually, changing the store URL back to ```localhost``` resolved the problem, though I'm not entirely sure why this fixed it.
