### ISSUE TITLE
GraphQL API for querying data from Medusa

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#663]
We want to add a GraphQL API layer for querying data from Medusa.

Generally, we see two approaches:
- Adding a GraphQL layer on top of our Rest API
- Adding a GraphQL layer, that communicated directly with our service layer

Research is required for this task, and all feedback is highly appreciated.

**Comment by sajov** [comment]
Hi there, great project!
In my personal opinion, GraphQL is not a one fit's all solution.
I have little reviewed the code base and just wondering why you guys didn't implemented a ORM and an API abstraction layer?
Do you know [feathersjs](https://feathersjs.com/)? We, at a bigger e-commerce company in Europe, use it heavily.

**Comment by coopbri** [comment]
Could someone point me to why Medusa doesn't support GraphQL or if there is a plan to implement it (natively, not e.g. with GraphQL Mesh plugging in the OpenAPI artifacts)? This issue was closed as "completed" but I assume that's not the case and it should've just been closed as not planned or similar

**Comment by coopbri** [comment]
Following up. Why not "not planned"? Match reality with what you're marketing, if this is still in ideation, mention it, if not planned mark as such
