### ISSUE TITLE
Create-medusa-app mislead input postgres username as database name

### ISSUE THREAD

**Issue by carafelix** [medusajs/medusa#6766]
### Describe the bug

After running `npx create-medusa-app@latest`, it fails to create a project if not having the same Postgres username as a database name. 
That's because the script is asking for a Postgres user and in reality is using that input as a postgres database name, and defaulting the username to `postgres` user

`"${Step3User}"` is used along the bug report as a variable for a valid Postgres username

### System information

Medusa version (including plugins): 1.20.2
Node.js version: 18.18.1
Operating system: Ubuntu 22.04 LTS

#### Pre-requisites:
- Have a running Postgres database server
- Have a valid user that have permissions to access that database

#### Steps: 
1. Run `npx create-medusa-app@latest`
2. Input valid project name, valid email for admin dashboard, next.js y/n
3. Script ask for `Enter your Postgres username`: Input valid Postgres user
4. Script ask for `Enter your Postgres password`: Input password of the user used in step 3

Script throws: 
`Couldn't connect to PostgreSQL because of the following error: error: database "${Step3User}" does not exist.`

Postgres server log:
```
[45] FATAL:  database "${Step3User}" does not exist
[44] FATAL:  password authentication failed for user "postgres"
[44] DETAIL:  Role "postgres" does not exist.
```

### Expected behavior

The script shouldn't expect the user and the database to have the same name. Script should ask for a username, a database name, and the user password.
At least the aforementioned question in step 3 shouldn't be `Enter your Postgres username` since as the postgres log shows, it's using that value for the database name, and not the user.

**Comment by shahednasser** [comment]
Thank you for opening this issue. Actually, if you refer to the code [here](https://github.com/medusajs/medusa/blob/60070fb65fa58872219a1145a8eace837f0cafde/packages/create-medusa-app/src/utils/create-db.ts#L70-L101), you'll find that the username and password are used correctly to connect to postgres, and the error is shown as returned by postgres while trying to connect.

It seems like your user isn't using the default database, one way to resolve this would be to either create a database for that user or set the `PGDATABASE` environment variable as explained in [Postgres's documentation](https://www.postgresql.org/docs/current/app-psql.html#R2-APP-PSQL-CONNECTING).

The reason we don't ask for a database is because we create a database for you. If you want to create your own database and use it instead, you can use the `--db-url <url>` option instead. Learn more in [our documentation](https://docs.medusajs.com/create-medusa-app#step-1-run-create-medusa-app).

Closing this for now, feel free to add to the issue if you run into other problems!
