### ISSUE TITLE
Shipping Methods don't get listed for cart based on requirements

### ISSUE THREAD

**Issue by WoodlegDev** [medusajs/medusa#7162]
### Describe the bug

When using the `store/shipping-options/{cart_id}` endpoint in our Medusa store, the API returns an empty array instead of listing the available shipping options based on the cart's requirements. This issue does not occur when using the `store/shipping-options` endpoint, which correctly displays all shipping options with their respective minimum and maximum cart requirements. Additionally, attempting to manually add a shipping option that does not meet the cart requirements correctly prevents the addition, indicating some functionality of the shipping logic works as intended.

### Steps to reproduce the behavior

1. Go to the Medusa store API endpoint `store/shipping-options/{cart_id}`.
2. Observe that the response is an empty array despite existing shipping options that should match the cart's criteria.
3. Compare with the results from the `store/shipping-options` endpoint where shipping options are displayed correctly.

### Expected behavior

The expected behavior is that the `store/shipping-options/{cart_id}` endpoint should return a list of available shipping options that match the current cart's requirements, similar to how the generic `store/shipping-options` endpoint operates.

### Screenshots

![image](https://github.com/medusajs/medusa/assets/67638254/09f62199-20a3-4994-b182-296847d4874d)
![image](https://github.com/medusajs/medusa/assets/67638254/411ba363-b6a5-4ed5-b8ba-e86003adf412)
![image](https://github.com/medusajs/medusa/assets/67638254/9f80f367-00e9-43d6-b1be-6acceeb94f27)
![image](https://github.com/medusajs/medusa/assets/67638254/0aa8de15-1f66-471f-b57e-fe1eb0199f2c)

**Comment by WoodlegDev** [comment]
issue still exists

**Comment by shiva05010** [comment]
@WoodlegDev Is this issue resolved? If yes, Can you explain how?

**Comment by scriptorShiva** [comment]
@WoodlegDev Is this issue resolved? If yes, how??

**Comment by WoodlegDev** [comment]
@scriptorShiva unfortunately not. We implemented for the time custom logic, but it's not optimal. It's not critical for us anymore - but in my experience help is better on the discord

**Comment by turistua** [comment]
> @scriptorShiva unfortunately not. We implemented for the time custom logic, but it's not optimal. It's not critical for us anymore - but in my experience help is better on the discord

did you implement your own logic to define which payment methods are applicable to your cart?

**Comment by scriptorShiva** [comment]
Yes, and also this issue is resolved by going through its implementation how its implemented. I get to know few points. This particular API using few methods as shown below before giving us result. 
so, most of the times if one of the function's condition did not match it return as empty array.

FOR DEBUG : You have to check all those functions in whichever service its calling and debug it accordingly.

In my case : 
a. Make sure shipping options you are creating add its subtotal cart min , max value and its should range between your cart total value. 
b. Everywhere in medusa when you are adding amount make sure add it by multiply with 100 and when you want to show it (show it by % by 100 so that it support decimal values ). 
![Screenshot_15](https://github.com/user-attachments/assets/bd9439ad-7f3e-4255-8d7f-ce004a1181f5)
