### ISSUE TITLE
Peer dependencies on medusajs/medusa

### ISSUE THREAD

**Issue by MrCasquette** [medusajs/medusa#7174]
### Describe the bug

 ```WARN  10 deprecated subdependencies found: @oclif/command@1.8.36, @oclif/config@1.18.16, @oclif/config@1.18.17, @oclif/config@1.18.2, @oclif/errors@1.3.5, @oclif/errors@1.3.6, @oclif/help@1.0.15, @oclif/parser@3.8.17, @oclif/screen@1.0.4, cli-ux@5.6.7```

 ```WARN  Issues with peer dependencies found
.
└─┬ @medusajs/medusa 1.20.4
  ├── ✕ missing peer typeorm@^0.3.16
  └─┬ medusa-test-utils 1.1.43
    ├── ✕ missing peer typeorm@^0.2.43
    └── ✕ unmet peer axios@^0.28.0: found 0.24.0 in @medusajs/medusa-js
✕ Conflicting peer dependencies:
  typeorm ```

### System information

Medusa version (including plugins): Only storefront client issue
Node.js version: v21.7.1
Operating system: MacOS

### Steps to reproduce the behavior

simply :

```pnpm i @medusajs/medusa-js```

### Expected behavior

Clear the dependencies issue and maybe the deprecated subdependencies (if possible in subdependencies hell ^^)

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
