### ISSUE TITLE
postgres database url ignoring the schema during seed

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#769]
I just setup Medusa in our project, and wanted to use the same database as our application logic, but with a different schema. I used this url:
`DATABASE_URL="postgresql://postgres:postgres@localhost:5432/nibllhome?schema=medusa"`

When I ran `medusa seed`, it generated all the medusa tables in the public schema instead of the `medusa` schema.

**Comment by srindom** [comment]
Have been researching a bit on the requirements for this and unfortunately, it seems that TypeORM (the ORM we use) could be more flexible on this topic. 

Let me try to break down what the issue is:

When we develop the Medusa core package and create database migrations using `$ typeorm migration:create` we get migration files that contain operations like this one: 

```javascript
    await queryRunner.query(
      `CREATE TABLE "tablename" (....)`
    )
```

When the `migration:create` command is being run TypeORM checks what schema the development machine's connection has, i.e. as a contributor to Medusa I could set up my dev TypeORM connection to use the "medusa" schema and that would then result in:
```javascript
    await queryRunner.query(
      `CREATE TABLE "medusa"."tablename" (....)`
    )
```

This obviously isn't very useful as that would just lock the possible schema to whatever the contributor's schema is (would also complicate the contribution flow so would rather avoid this).

So to sum up the issue is basically that the TypeORM connection doesn't control under what schema the migrations will run under but only controls the connection being made to the database and what table names to give to generated migrations.

To come up with a solution that could work I think we would have to do something along the lines of "dynamically" running the migrations based on the configured schema in the database connection. This would require us to change all current migrations to this form:
```javascript
    await queryRunner.query(
      `CREATE TABLE ${medusaConfig.database_connection.schema}."tablename" (....)`
    )
```
_Disclaimer: The above snippet might not follow the exact structure needed and as far as I remember using string interpolation in SQL queries is bad practice so don't take the above as a direct implementation, but rather as an illustration of an idea :D_ 

Would love if someone could find some time to test the above idea  :)

**Comment by isaachinman** [comment]
Been quite awhile since this issue was opened – any update?

I'm also attempting to add Medusa to an existing application (Node/Express/Prisma/Postgres), and the functionality described here is absolutely essential.

I imagine that most existing production applications are not able/willing to create a completely separate Medusa service, as that increases operational complexity and splits business logic up.

**Comment by dwene** [comment]
Hey @isaachinman 

As far as I know, this issue is still unresolved. I was also attempting to add Medusa to an existing nest/express/prisma service. In the end for this particular client, I found it was easier to just treat Medusa as a microservice, and create a new database in the same postgres server for Medusa.

Alternatively, if your existing application isn't too terribly large, you can migrate your existing business logic to Medusa Extender. That's what we are doing these days for any custom business logic needed in the same api as Medusa.

**Comment by rickylabs** [comment]
Any news on this ?

I'm still getting that kind of issue when schema is set to something else than "public"
`query failed: CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))
error: error: permission denied for schema public`

Very annoying and I think this should be addressed since some companies like ours who need to add medusa data to an existing DB will need the ability to properly set a custom schema in Postgres

**Comment by adrien2p** [comment]
Hi there. We highly appreciate you filing an issue and showing an interest in improving Medusa.

I apologize for the delayed response.

Moving forward, we aim to do better. But we would like to start fresh. Therefore, we are considering all older issues as stale and closing them, even though they might still be relevant.

Please don't hesitate to re-open the issue (or create a new one) if you still need a resolution or an answer.

Thanks ❤️

**Comment by isaachinman** [comment]
Pretty typical OSS "management" these days... Rinse and repeat

**Comment by adrien2p** [comment]
as mentioned, this is a limitation of the ORM that we are using under the hood, this is likely to evolve as we are moving to modules and using a different ORM. for this particular case as mentioned by dwene it is easier to treat it as a separate service. Unfortunatelly we don't have the hand on Typeorm to do those kind of changes.
