### ISSUE TITLE
Product thumbnail removed from product images on create.

### ISSUE THREAD

**Issue by HarleySalas** [medusajs/medusa#8458]
### Describe the bug

Upon creating a product and uploading product images, selecting a thumbnail during the product creation process causes the selected image (thumbnail) to not be visible on the product page, as a product image. (See NextJS starter product page after creation, or API response) In order to resolve the situation, you must set another image as the thumbnail, then revert to your original (proper) thumbnail. Only then, will you have a thumbnail set, as well as all of your product images visible on the product page.

### System information

Medusa version (including plugins): `preview-20240803120600`
Node.js version: `22.2.0`
Database: `Postgres 16.3`
Operating system: `Linux Mint 21.3 Cinnamon`
Browser (if relevant): `Chrome Version 126.0.6478.114 (Official Build) (64-bit)`

### Steps to reproduce the behavior

1. Create a product.
2. Upload images during the product creation process.
3. Set one of those images as the thumbnail.
4. Finish creating product.
5. Observe product page to see that the thumbnail is absent from the product images.
6. Switch to a different thumbnail, then revert to the original in order to see all product images visible on the product page.

### Expected behavior

Setting an image as a thumbnail should not remove it from product images.

### Additional context

I also find it quite irritating that you cannot reorder image uploads/product images.

**Comment by srindom** [comment]
Hi @HarleySalas - it is expected behavior that the thumbnail doesn't get added to the product images. It's common for example to have a thumbnail that is cropped differently from other product images. 

I do, however, understand your expectation considering the current UX flow for uploading and selecting thumbnails. I will close this issue for now, but create a task to revisit the product media management so we have a flow that is more intuitive than the current one. We will also take a look at reordering ;)

Thanks for reporting!

**Comment by HarleySalas** [comment]
Understood, I had that in mind as well, but assumed they were "shared" considering the fact that they are uploaded together and there was this sort of inconsistency. Don't forget about the part where the thumbnail **is** included in the product images (after switching the thumbnail, then switching back), so even with your intended functionality, there is still a bug, where thumbnail handling is completely inconsistent.
