### ISSUE TITLE
Unable to Refund Payment for an Order - "Order does not have an outstanding balance to refund" Error

### ISSUE THREAD

**Issue by vholik** [medusajs/medusa#9261]
## Bug report

Unable to Refund Payment for an Order - "Order does not have an outstanding balance to refund" Error

### Describe the bug

When attempting to refund a payment using the admin panel, I receive the error: "Order does not have an outstanding balance to refund". Adjusting the refund amount to 0 does not resolve the issue.

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
You cannot issue ad-hoc refunds on orders. There needs to be an imbalance (as the message states), e.g. as a result of an exchange or a return, as it would otherwise open up for a range of accounting-related issues that we do not want to deal with right now.

That said, this is in our backlog and will likely be tackled some time after the official release.

**Comment by turistua** [comment]
@olivermrbl is this planned now? The use case can be when customer asks for some partial refund as compensation (e.g. product was delivered damaged, but customer is happy to keep it)

**Comment by jungsikjeong** [comment]
So, has this issue been resolved?
In my case, I used the test payment method 'pp_system_default' and captured the payment, then tried to issue a refund from the admin dashboard, but I got the error: Order does not have an outstanding balance to refund.
Is this because it's a test payment or a manual payment method?

**Comment by AnthonyGhizzo** [comment]
I have the same problem.

**Comment by FatherOctber** [comment]
Why the issue was closed? It`s actual for me. My store used:
     "@medusajs/admin-sdk": "2.8.8",
    "@medusajs/cli": "2.8.8",
    "@medusajs/framework": "2.8.8",
    "@medusajs/medusa": "2.8.8",

<img width="1193" height="836" alt="Image" src="https://github.com/user-attachments/assets/78f2d03e-8110-4772-a8ff-f2532f4b5ff5" />

It`s manual payment channel. So how I can fixed it?

Maybe I have not quite understood the case and the order have been already partitioned  refunded?

**Comment by bestK** [comment]
<img width="562" height="940" alt="Image" src="https://github.com/user-attachments/assets/7ba0ce46-2dd4-444a-adfe-e8a5454ada01" />

I have the same issue with PayPal

**Comment by olivermrbl** [comment]
Our next release will introduce manual refunds, which should solve your issues. It allows you to issue refunds without having a returning value on the order.
