### ISSUE TITLE
error:   Errors while loading module providers for module payment

### ISSUE THREAD

**Issue by Attachai77** [medusajs/medusa#9599]
### Describe the bug

I've updated latest rc5 (2.0.0-rc-20241015170251) for Medusa Backend and I getting this error.

<img width="1049" alt="Screenshot 2567-10-16 at 08 24 24" src="https://github.com/user-attachments/assets/88241500-b8b0-43df-8499-566bcf11e264">

I've discussed  some contributor in Discord (https://discord.com/channels/876835651130097704/1295803708629581914), they think it's loader issue. 

### System information

Medusa version (including plugins):
Node.js version: 20.12.2
Database: postgresql
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to 'update latest rc (2.0.0-rc-20241015170251)' and run 'yarn dev'
2. See error

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by jakub-borek** [comment]
Same thing happens with custom notification providers

![image](https://github.com/user-attachments/assets/e68527e2-1325-4140-a92a-2e68b26a8a90)

**Comment by zaidrashid** [comment]
After updating to rc5 I've got this issue on my custom auth provider. 

![image](https://github.com/user-attachments/assets/d4bd911f-caed-43f4-a592-687ec3c328a5)

How are your `medusa-config.js` file look like? I'm a bit lost now since all the documents show examples in `medusa-config.ts` (typescript). Anwyay, my config file is following [this](https://docs.medusajs.com/v2/resources/references/auth/provider#4-use-module)

**Comment by olivermrbl** [comment]
@zaidrashid, we are looking into this. Will get back asap!

**Comment by olivermrbl** [comment]
We've patched this in the latest RC :)

**Comment by zaidrashid** [comment]
@olivermrbl Thanks! It's working on my end.
