### ISSUE TITLE
Can not remove entity in payment_providers table

### ISSUE THREAD

**Issue by Twilight-0205** [medusajs/medusa#9600]
I wrote a migration to remove several entities like stripe-przelewy24, stripe-ideal, etc. When the migration was executed on the database, it successfully deleted those entities. However, each time I build and run the Medusa store, they automatically get inserted back into the database

**Comment by olivermrbl** [comment]
Every time we load the application, we check if there are any unregistered payment providers by scouring your Medusa config for payment providers. If there are, we will register them (i.e. add them to the database). Consequently, if you delete payment providers, they are re-added on the next application bootstrap.

Can you tell me more about your setup, because from the looks of it, this is expected behavior?
