### ISSUE TITLE
Unable to get started with medusajs

### ISSUE THREAD

**Issue by olawale-o** [medusajs/medusa#9836]
### Describe the bug

Could not resolve module: Workflows. Error: Loaders for module Workflows failed: Invalid URL

### System information

Medusa version (including plugins):
Node.js version: v20.17.0
Database: postgresSQL
Operating system: MacOs BigSur
Browser (if relevant):

### Steps to reproduce the behavior

1. npx create-medusa-app@latest
2. sudo yarn dev
![Screen Shot 2024-10-28 at 11 23 33](https://github.com/user-attachments/assets/ef2a86b4-5662-4305-8b0f-f98a2d0673fd)
![Screen Shot 2024-10-28 at 11 23 40](https://github.com/user-attachments/assets/943607f7-6d93-4405-9b8e-663a36880277)

**Comment by Mohmdev** [comment]
I had the same problem. After a series of trials and errors, I found the reason to be `NODE_ENV`. Since a few updates back, we were able to set it as `production` and I had kept it that way. However, since some of the recent updates, including the latest 2.0.0 and 2.0.1, `NODE_ENV=production` doesn't work anymore.
The server starts successfully only when `NODE_ENV` is set to `development`.
I could be wrong though, but this is how I was able to get mine to start.

**Comment by olawale-o** [comment]
Hi @Mohmdev 
It is not working. Thank you for the response. I also have an issue of starting the server with `sudo yarn dev`. command I wouldnt know if that is the standard. However, this is my first time of working with medusa.

**Comment by medusastore** [comment]
Same problem here, server on deplyoment only start when node_env is set to development, when set to production in worker mode server this error appear.

**Comment by sradevski** [comment]
Hi @olawale-o can you please upgrade to the latest version and see if this is still an issue?

**Comment by sradevski** [comment]
Closing as there hasn't been any response to it.
