### ISSUE TITLE
Auth Module - Can't get user's email after successful callback validation.

### ISSUE THREAD

**Issue by jgatto1** [medusajs/medusa#9847]
### Describe the bug
I'm implementing a custom auth module, all is working great, but I can't get the user metadata like email after a successful `/callback` response. In your docs it says:
> // TODO show form to retrieve email from customer

But I think the response should contain more data than a token to avoid adding a new step in the UI (input field).

**Edit**: This can also be really helpful in the case I want to login an `admin` user, because according to this flow [here](https://docs.medusajs.com/resources/commerce-modules/auth/authentication-route) I need to accept an invite and the invite should be created on the server side first, then I'd return the `inviteId`:
![image](https://github.com/user-attachments/assets/36d53c17-4190-4f5e-a93c-8b65be930702)

So this fix/improvement would help both, `users` and `customers`. 😄 

What do you think?

Thanks!

### System information

Medusa version (including plugins): 2.0.0
Node.js version: v20.17.0
Database: 13.16-1.pgdg120+1
Operating system: MacOS 14.0 (23A344)
Browser (if relevant):

### Steps to reproduce the behavior

Implement custom auth module and configure OAuth. Same as Google Login.

### Expected behavior

It should return the user metadata to avoid a new UI input in the whole flow.

**Comment by Shriz07** [comment]
I also think user_metadata passed during invoke of authIdentityService.create... should be saved in token (maybe even provider_metadata too).

I tried to inject ICustomerModuleService to create user while authenticating with 3-rd party provider so that there will be no need to send request from FE to create user but unfortunately injection doesn't work and provider stops to work when I do so...

**Comment by Shriz07** [comment]
@jgatto1 You can use createCustomerAccountWorkflow() to create customer in your auth provider, just remember to retrieve auth identity again (authIdentityService.retrieve({entity_id})) before returning it so that token will contain customer context. If you do so then there will be no need to send request from frontend app to create customer.

**Comment by jgatto1** [comment]
@Shriz07 did your code work? I tried using workflows for creating new users but I got `unauthorized`

**Comment by jgatto1** [comment]
@Shriz07 thanks great idea! Maybe the docs are a bit unclear, but we all know that there could be some fixes/bugs/improvements 😃
