### ISSUE TITLE
No default Locking provider explicit defined

### ISSUE THREAD

**Issue by MrCasquette** [medusajs/medusa#9919]
### Describe the bug

No default locking provider explicit defined (No idea how to define it)
Work in dev mode not in production
(same server and config only the script changes so probably also node env)

### System information

Medusa version : 2.0
Node.js version: v20.18.0
Database: Postgres on docker container
Operating system: Debian

### Steps to reproduce the behavior

Use :
- pnpm
- pm2
- redis as it's described in the doc :
https://docs.medusajs.com/resources/architectural-modules/event/redis#main
https://docs.medusajs.com/resources/architectural-modules/workflow-engine/redis#main
https://docs.medusajs.com/resources/architectural-modules/cache/redis#main
 then build and start on pm2
 
### Expected behavior

Just my dashboard to be available

### Additional context

Here's the dev log :

```
info:    Skipping instrumentation registration. No register function found.
info:    Connection to Redis in module 'cache-redis' established
info:    Connection to Redis in module 'event-bus-redis' established
info:    Connection to Redis in module 'workflow-engine-redis' established
info:    Connection to Redis PubSub in module 'workflow-engine-redis' established
warn:    No default locking provider explicit defined. Using "in-memory" as default.
info:    No job to load from /home/shannon/dpc/medusa/node_modules/.pnpm/@medusajs+medusa@2.0.1_t54ea27v67fqr5ahlkeyscflri/node_modules/@medusajs/medusa/dist/jobs. skipped.
info:    Generated modules types
✔ Server is ready on port: 9000 – 21ms
```

And the production log :
```
> medusa-starter-default@0.0.1 start /home/shannon/dpc/medusa
> medusa start

{"level":"info","message":"Skipping instrumentation registration. No register function found.","timestamp":"2024-11-03 19:58:58"}
{"level":"info","message":"Connection to Redis in module 'cache-redis' established","timestamp":"2024-11-03 19:58:58"}
{"level":"info","message":"Connection to Redis in module 'event-bus-redis' established","timestamp":"2024-11-03 19:58:58"}
{"level":"info","message":"Connection to Redis in module 'workflow-engine-redis' established","timestamp":"2024-11-03 19:58:59"}
{"level":"info","message":"Connection to Redis PubSub in module 'workflow-engine-redis' established","timestamp":"2024-11-03 19:58:59"}
{"level":"warn","message":"No default locking provider explicit defined. Using \"in-memory\" as default.","timestamp":"2024-11-03 19:58:59"}
{"level":"info","message":"No job to load from /home/shannon/dpc/medusa/node_modules/.pnpm/@medusajs+medusa@2.0.1_t54ea27v67fqr5ahlkeyscflri/node_modules/@medusajs/medusa/dist/jobs. skipped.","timestamp":"2024-11-03 19:59:02"}
{
    "level": "error",
    "message": "Error starting server",
    "stack": [
        {
            "columnNumber": 11,
            "fileName": "/home/shannon/dpc/medusa/node_modules/.pnpm/@medusajs+admin-bundler@2.0.1_@babel+runtime@7.26.0_@types+node@20.17.6_@types+react-dom@18.3_ula5o4qawbyfjv65tqurclwuuq/node_modules/@medusajs/admin-bundler/dist/index.js",
            "functionName": "serve",
            "lineNumber": 1344,
            "methodName": null,
            "native": false,
            "typeName": null
        },
        {
            "columnNumber": 28,
            "fileName": "/home/shannon/dpc/medusa/node_modules/.pnpm/@medusajs+medusa@2.0.1_t54ea27v67fqr5ahlkeyscflri/node_modules/@medusajs/medusa/src/loaders/admin.ts",
            "functionName": "serveProductionBuild",
            "lineNumber": 75,
            "methodName": null,
            "native": false,
            "typeName": null
        },
        {
            "columnNumber": 3,
            "fileName": "/home/shannon/dpc/medusa/node_modules/.pnpm/@medusajs+medusa@2.0.1_t54ea27v67fqr5ahlkeyscflri/node_modules/@medusajs/medusa/src/loaders/index.ts",
            "functionName": "async loadEntrypoints",
            "lineNumber": 108,
            "methodName": null,
            "native": false,
            "typeName": null
        },
        {
            "columnNumber": 31,
            "fileName": "/home/shannon/dpc/medusa/node_modules/.pnpm/@medusajs+medusa@2.0.1_t54ea27v67fqr5ahlkeyscflri/node_modules/@medusajs/medusa/src/loaders/index.ts",
            "functionName": "async exports.default",
            "lineNumber": 164,
            "methodName": "default",
            "native": false,
            "typeName": "async exports"
        },
        {
            "columnNumber": 50,
            "fileName": "/home/shannon/dpc/medusa/node_modules/.pnpm/@medusajs+medusa@2.0.1_t54ea27v67fqr5ahlkeyscflri/node_modules/@medusajs/medusa/src/commands/start.ts",
            "functionName": "async internalStart",
            "lineNumber": 120,
            "methodName": null,
            "native": false,
            "typeName": null
        },
        {
            "columnNumber": 5,
            "fileName": "/home/shannon/dpc/medusa/node_modules/.pnpm/@medusajs+medusa@2.0.1_t54ea27v67fqr5ahlkeyscflri/node_modules/@medusajs/medusa/src/commands/start.ts",
            "functionName": "async start",
            "lineNumber": 221,
            "methodName": null,
            "native": false,
            "typeName": null
        }
    ],
    "timestamp": "2024-11-03 19:59:02"
}
```

I do not have more infiormations anymore as I delete this session that I cannot use on production sorry I should have picked more context before deleting the project.

**Comment by Deroswent** [comment]
have the same issue

**Comment by olivermrbl** [comment]
@triplecasquette, the locking provider log is just a warning and is unrelated to your issue. We will work on including some information about the locking concept for our documentation to provide some clarity.

The error you are seeing seems to be related to the admin dashboard. Could you provide a reproduction in a repository and we will take a look at it?

**Comment by Mohmdev** [comment]
> @triplecasquette, the locking provider log is just a warning and is unrelated to your issue. We will work on including some information about the locking concept for our documentation to provide some clarity.
> 
> The error you are seeing seems to be related to the admin dashboard. Could you provide a reproduction in a repository and we will take a look at it?

Hello @olivermrbl,

So many people including myself have reported that the admin dashboard fails to start in production since the 2.0.0 release.
Another major drawback for Medusa v2 is the lack of support for a search indexing engine like the old `medusa-plugin-meilisearch`. What good is a commerce engine without proper search functionality?
3rd, I had been developing on top of the v2 storefront-starter during the preview and rc releases only to be prepared for the `latest` release. But ever since the `latest` releases, everything seems to have been broken. I dont know why or how, but the very same storefront now has so many major problems which I assume are coming from the backend.

The only update since 2 weeks ago has been v2.0.1 but that didnt seem to fix anything. Moreover, there hasn't been much feedback or clarity on all these issues that are being reported repeatedly. I can only assume that the medusa team has been busy working on the new medusa cloud. But please, look into these major problems because at this point, the choices are either the old medusa v1 or just opting for other commerce frameworks/platforms.

I write this to you Oliver because of the many many hours that I have invested in medusa v2 (specially the storefront part) and now things barely work. I am sure many other devs share the same frustrations as me. Just look into the issues please.

**Comment by Deroswent** [comment]
Despite the “production ready” release - medusa v2 is absolutely not ready to work and contains many bugs.
A vivid example - the shopping cart doesn't work https://github.com/medusajs/medusa/issues/9755#issuecomment-2454521827 .  And this is one of the basic functions of the application for trading.  This problem is already more than two weeks old, and the developers have not fixed it.

**Comment by olivermrbl** [comment]
@Deroswent, this comment is not relevant to this issue, so I'll remove it. We are aware of the issue you are referring to and will be working on a fix in the near future. There are only so many things we can do, and we are a small team. Patience is appreciated.

**Comment by adrien2p** [comment]
Hi guys, the issue for which this ticket has been open is link to the way production build should be started. In order to fix this issue, I would suggest to have a read on this documentation section [here](https://docs.medusajs.com/resources/medusa-cli/commands/build#run-built-medusa-application) . Long story short, the main thing to remember about production ready build is to move to the correct location and eventually cp the env file if needed (usually in the case of VPS or local testing with production flag)

**Comment by olivermrbl** [comment]
> So many people including myself have reported that the admin dashboard fails to start in production since the 2.0.0 release.

@Mohmdev, could you please reference the issues you are describing here? We are happy to look into it.
